### ISSUE TITLE
Port determination method is inconsiderate of reverse proxying

### ISSUE THREAD

**Issue by dpoon** [apereo/mod_auth_cas#105]
In [`getCASService()`](https://github.com/Jasig/mod_auth_cas/blob/v1.1/src/mod_auth_cas.c#L546) and [`cas_authenticate()`](https://github.com/Jasig/mod_auth_cas/blob/v1.1/src/mod_auth_cas.c#L2035), among other places, the TCP port is determined using `r->connection->local_addr->port`.

While this gives us the port of the server side of the TCP connection, it is not necessarily the port that the user agent connected to.  The difference is that if the Apache server is behind a reverse proxy (such as a load balancer), then `r->connection->local_addr->port` gives the port of the last hop (labelled "backend connection" in the diagram below), which is irrelevant to the CAS authentication process.  What matters is the URL of the resource that the user agent wants to access.

```
                             Reverse proxy                     Apache with mod_auth_cas
┌────────────┐ Primary ┌───────────────────────┐            ┌────────────────────────────┐
│ User agent │────────→│443                    │            │                            │
└────────────┘ request │  https://example.com  │  Backend   │ http://farm1.internal:3141 │
                       │                       │───────────→│3141                        │
                       └───────────────────────┘ connection └────────────────────────────┘
```

By using `r->connection->local_addr->port`, `getCASService()` will construct `https://example.com:3141` as the service URL, which the CAS server will likely not recognize.  Then, even if the authentication succeeds, `cas_authenticate()` will redirect the user agent to `https://example.com:3141`, where there is no web server running.

The more appropriate replacement for `r->connection->local_addr->port` is [`ap_get_server_port(r)`](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__HTTPD.html#ga1000d24d1fa084f1908eb9af1a41db5e): the Apache function to "get the current server port".  That function consults `server_rec->port`, which is the same way that [CGI establishes the `SERVER_PORT` environment variable](http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.0/server/util_script.c?revision=1232070&view=markup#l234) and mod_php establishes `$_SERVER['SERVER_PORT']`, and how URLs are constructed in various places within Apache (such as in [`mod_auth_digest.c`](http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.0/modules/aaa/mod_auth_digest.c?revision=1232070&view=markup#l1648).  Then, if there is a reverse proxy, a module such as [mod_rpaf](https://github.com/gnif/mod_rpaf/blob/v0.8.4/mod_rpaf.c#L363) would likely override `server_rec->port` to do the right thing.

---

_Side note:_ It should be possible to take advantage of [`ap_is_default_port()`](https://ci.apache.org/projects/httpd/trunk/doxygen/group__APACHE__CORE__DAEMON.html#gae5bc38a44a7c51bef163b8208559f3a1) instead of hard-coding 80 and 443 [here](https://github.com/Jasig/mod_auth_cas/blob/v1.1/src/mod_auth_cas.c#L565) and [here](https://github.com/Jasig/mod_auth_cas/blob/v1.1/src/mod_auth_cas.c#L2110).

**Comment by dhawes** [comment]
Have you looked at `CASRootProxiedAs`?

For your example you would want to set `CASRootProxiedAs https://example.com` to get the proper service URL.

I think you're right that there may be improvements that can be made here, and I'll be sure to investigate them further. In the meantime do you have any use cases that `CASRootProxiedAs` won't address?

**Comment by aanli** [comment]
I have this bug

**Comment by dhawes** [comment]
Have you tried CASRootProxiedAs?

On Dec 23, 2016 10:30 AM, "Aymar Anli" <notifications@github.com> wrote:

I have this bug

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Jasig/mod_auth_cas/issues/105#issuecomment-269005808>,
or mute the thread

**Comment by aanli** [comment]
CASRootProxiedAs fixes the problem.
Thanks!!
