### ISSUE TITLE
Simple way to force the CASCache to be totally wiped out ?

### ISSUE THREAD

**Issue by dbz78** [apereo/mod_auth_cas#107]
Hello,
With colleagues in my company, we are currently trying to fix issues with an application relying on mod_auth_cas for authentication. Problems are related to certificates.
For some reasons, the application is running on a Windows platform (not the best choice from my point of view).
In order to verify various possibilities, we have to stop Apache service, modify certificate files, restart Apache service, do some testing, try to understand traces in log files and failing behavior from the end user point of view.

After doing some testing, we are puzzled. The behaviour is not as expected, which means: sometime we expect the ticket validation to NOT work, but it works ; sometime we expect it to work, and it doesn't.

Considering debug information in the Apache error.log, we wonder whether there could be some caching issue disturbing our tests. Traces show messages like:

> entering createCASCookie()
> entering CASCleanCache()
> Beginning cache clean
> Processing cache file '003804ec667d42f309de1adb6348fc14'
> entering readCASCacheFile()
> entering deleteCASCacheFile()
> entering readCASCacheFile()
> Removing expired cache entry '003804ec667d42f309de1adb6348fc14'
> entering writeCASCacheEntry()
> entering readCASCacheFile()
> Processing cache file 'd95bf315dea2af9eea8a4d45c488cd1e'
> entering readCASCacheFile()
> entering writeCASCacheEntry()
> Cookie '6101dcbbc1a1162f29baf424b467d950' created for user 'username'
> entering setCASCookie()
> ...

We wonder if this CASCache feature is not the culprit for strange, unexpected behaviour. Some user sessions' information previously validated would remain, then the user would be authenticated though certificate file has been changed?
A clue to confirm this is that, if we wait long enough before doing some new tests, possibly overcoming timeouts (**CASTimeout**, **CASIdleTimeout**, **CASCacheCleanInterval**), behaviour seems more logical.

Question: Is there a simple way to force the CASCache to be totally wiped out, when needed after some important configuration change (here, certificate file replacement)?

Thanks for any answer or feedback,

**Comment by dhawes** [comment]
> We wonder if this CASCache feature is not the culprit for strange, unexpected behaviour. Some user sessions' information previously validated would remain, then the user would be authenticated though certificate file has been changed?

I'm not following something here. What certificate is changing, and why do you think that would affect validation?

Can you give a clear example of some of this unexpected behavior? This will help us determine if there is an issue here. The interplay of client cookies with the server cache and timeouts can be confusing. I'd like to see if we can explain what is going on.

> Question: Is there a simple way to force the CASCache to be totally wiped out, when needed after some important configuration change (here, certificate file replacement)?

Simply rm everything in CASCookiePath. This is how I typically test things.

**Comment by dbz78** [comment]
dhawes, thanks for your reply

The certificate we want to change is the one that mod_auth_cas, acting as a CAS client on behalf of connected users, uses to interact with CAS server to validate Service Tickets. We must change it since we will soon reach expiration date of former certificate and must change Certificate Authorities' chain for security reasons.

It is very difficult to explain what should happen and what happens. Since I wrote my comment, we have had some review. We wonder whether one of or CAS servers in the farm would be faulty and not configured like others. This requires thorough investigation, more on this soon...

We will also try cleaning the CASCookiePath, and see if things get more logical then.

Thanks,

**Comment by dhawes** [comment]
Changing the CASCertificatePath, while requiring an Apache restart, does not invalidate any mod_auth_cas session data.

If you expected the session data to be invalidated maybe that could explain some of the behavior you are experiencing?
