### ISSUE TITLE
i found multiple MOD_AUTH_CAS values in cookie 

### ISSUE THREAD

**Issue by isoloist** [apereo/mod_auth_cas#112]
when i access different urls in the same application.  

<IfModule mod_auth_cas.c>
    CASLoginURL http://xxxxxxx
    CASVersion 2
    CASDebug On
    CASValidateURL http://xxxxxxx
    CASCookiePath  /xx/xxx
    CASTimeout 43200
    CASIdleTimeout 3600
</IfModule>

<Location />
    AuthType CAS
    Require valid-user
</Location>

**Comment by dhawes** [comment]
Can you supply more information?

Do you or did you have CASScope set?

What are the path values for the cookies?

What version of mod_auth_cas are you running?
