### ISSUE TITLE
Request ability to uppercase or lowercase a userid

### ISSUE THREAD

**Issue by mddvul22** [apereo/mod_auth_cas#123]
We have a mod_auth_cas 1.1 implementation running on a Red Hat 7 server.  We have an application authenticating against a CAS server that we don't have control over, where the majority of users are passed to the application in uppercase.

However, that same CAS server passes some users in lowercase.  It would be ideal if there was a way in mod_auth_cas to convert all usernames to either uppercase or lowercase, overriding what the CAS authentication server sends?

We can address this in our application.  However, we are ALSO making use of the AuthGroupFile Apache option to control authorization of authenticated users coming from that CAS server.  Given that this Apache option is case sensitive, and that we can't control/predict how the external CAS server manages the case of these usernames, it would be ideal for mod_auth_cas to be able to lower- or upper-case the usernames.

Thanks.

**Comment by dhawes** [comment]
A similar request came across the cas-user list recently:

https://groups.google.com/a/apereo.org/d/msg/cas-user/0jrl9JWkqMc/lgD07HVsGAAJ

I'm certainly open to this and it seems like a straightforward request. I'll wait and see if anyone else wants to weigh in before implementing it.

**Comment by mddvul22** [comment]
Hi David, anything we can do to assist with the implementation of this?  Thanks!

**Comment by dhawes** [comment]
Contributions are always welcome in the form of merge requests. That's certainly the most direct way to assist. If you want to give it a shot, please let me know. Otherwise, I don't think this will take too much time and is on my list.

**Comment by dhawes** [comment]
I'm not sure mod_auth_cas is the right place for this and I haven't heard of other users needing this. If it's something you'd still like to see, a PR is the way to go.
