### ISSUE TITLE
It is surprising that CASAuthNHeader is per-directory but CASAttributePrefix is not

### ISSUE THREAD

**Issue by maxb** [apereo/mod_auth_cas#124]
CASAttributePrefix and CASAuthNHeader both define header names to which the module should add information - yet one is per-directory and one is not.

This seems fairly unexpected. It's not really an issue for me, and is realistically unlikely to bother many people at all, but it's a surprising design choice/accident.

**Comment by dhawes** [comment]
This was brought up in a previous issue:

https://github.com/Jasig/mod_auth_cas/issues/102#issuecomment-230038836

It's never been an issue for me either, so I could really go either way.

**Comment by dhawes** [comment]
The documentation was updated.
