### ISSUE TITLE
plans on new release

### ISSUE THREAD

**Issue by carazzim0** [apereo/mod_auth_cas#127]
Hi there,

are there any plans on a new release since it has already been over a year since last release?

Thanks & regards,
carazzim0

**Comment by dhawes** [comment]
There aren't any plans right now, but there have been a few commits that I think would warrant a new release, especially the CASv2 attributes.

There are a couple of configuration-type issues I'd like to knock out before doing so, but I'll do my best to work towards that.

**Comment by lchanouha** [comment]
Hi, any plan to release 1.2 soon ?
i have in mind Debian 10 full freeze on march 2019. Would be nice to have it on repos on upgrade :)

Regards,
L.

**Comment by thijskh** [comment]
A release would indeed be most welcome. Thanks!

**Comment by dhawes** [comment]
I hope this isn't too far away.

It'll definitely have:

#103 
#104 
#109
#89 
#110 
#120 
#135 
#150 
#153 
#156 
#155

Probably:

#161 
#158 
#146 
#138 

Possibly:

#132

**Comment by yakatz** [comment]
Also wanted to voice support for a release that would include #106. We hit this issue today - turning on full debug logging causes us auditing trouble, so it would be nice to filter by module.

**Comment by adaugherity** [comment]
Things which would be nice to have in the next release:
* building without forcing autoreconf, or better yet, without requiring any autoconf/automake (leaving autoreconf as a last resort, of course)
  *  also, running autoreconf creates a lot of dirty files in the git checkout
* a stable release tarball, checksummed and/or signed -- apparently GitHub's autogenerated tarballs [are _not_ guaranteed to be consistent](https://marc.info/?l=openbsd-misc&m=153492430016386&w=2), as different backend hosts, zlib upgrades on their servers, etc. could change a few bits, but if you create a release and upload _your own_ tarball to it, that file will stay consistent.

**Comment by cmurtaugh** [comment]
We'd love to see a new release that included #132!

**Comment by dhawes** [comment]
@yakatz PR #109 covers issue #106.

@cmurtaugh I'm debating adding a directive to limit the response size to assuage the concerns in #132. Do you find that acceptable? There'd be a limit, but it would controllable in config rather than having to recompile like you have to do now.

**Comment by cmurtaugh** [comment]
@dhawes A configurable response size limit would be perfect.  Thanks!

**Comment by dhawes** [comment]
>     * building without forcing autoreconf, or better yet, without requiring any autoconf/automake (leaving autoreconf as a last resort, of course)       
>       * also, running autoreconf creates a lot of dirty files in the git checkout

I'll give this a look before the next release. 

>     * a stable release tarball, checksummed and/or signed -- apparently GitHub's autogenerated tarballs [are _not_ guaranteed to be consistent](https://marc.info/?l=openbsd-misc&m=153492430016386&w=2), as different backend hosts, zlib upgrades on their servers, etc. could change a few bits, but if you create a release and upload _your own_ tarball to it, that file will stay consistent.

At the very least we could probably sign the release tags.

**Comment by dhawes** [comment]
My hope is to have a release by the end of this month. Does that fit the Debian time line?

Updated list:

Definitely:

#103
#104
#109
#89
#110
#120
#135
#150
#153
#156
#155
#161
#138
#132
#158

Probably:

#146

**Comment by thijskh** [comment]
Maybe add them to a Github milestone so it’s immediately clear what is done and what still open.

**Comment by dhawes** [comment]
https://github.com/apereo/mod_auth_cas/milestone/6

**Comment by dhawes** [comment]
I've tagged v1.2-RC1. [1]

If you'd like to help with testing, please pull, test, and comment (this issue is fine).

[1] https://github.com/apereo/mod_auth_cas/tree/v1.2-RC1

**Comment by lchanouha** [comment]
Thank you @dhawes. I sent a mail to Debian's maintainer (Thijs Kinkhorst).
I will try RC1 from next week.

(https://tracker.debian.org/pkg/libapache2-mod-auth-cas)

**Comment by dhawes** [comment]
v1.2-RC2 tagged:

https://github.com/apereo/mod_auth_cas/tree/v1.2-RC2

**Comment by dhawes** [comment]
v1.2 tagged:

https://github.com/apereo/mod_auth_cas/tree/v1.2

@adaugherity I looked at autoconf but did not make any changes for now. I do plan on revisiting it in the future.
