### ISSUE TITLE
Move from Jasig to Apereo?

### ISSUE THREAD

**Issue by mmoayyed** [apereo/mod_auth_cas#128]
Howdy folks,

I would like to move this project from jasig to apereo on Github. The transfer is going to preserve all history, settings, forks and clone. It will be business as usual, except that the project will be hosted under an org on Github that actually is relevant and does exist. 

Please let me know if you see any issues with this plan. I would like to get this done before the upcoming weekend. 

Thanks.

**Comment by forsetti** [comment]
Does "move" mean cloning the repo to the new location, and sometime later,
deleting the current location? Or does "move" mean a location change?
I.e., will the URL immediately change for downstream packagers?

**Comment by mmoayyed** [comment]
Move essentially is like a "rename" operation where the old name continues to work fine.

The URL will not change for the downstream systems; both URLs however will simply continue to work fine. 

This works:

```
git clone https://github.com/Jasig/mod_auth_cas.git`
```

So does this:

```
https://github.com/Apereo/mod_auth_cas.git
```

If you use the old one, you might get a gentle warning.

And if you access `https://github.com/Jasig/mod_auth_cas/` you will be immediately redirected to `https://github.com/Apereo/mod_auth_cas/`.

**Comment by forsetti** [comment]
This works for me.  As long as the previous URL is preserved for a while,
and no one else can take it over and do something malicious with it, then
let's do it.  Need to also get an ACK from +dhawes first.

**Comment by dhawes** [comment]
Ack. Sounds good to me.

**Comment by mmoayyed** [comment]
Thank you all. We are done. LMK if you run into any issues.
