### ISSUE TITLE
CASGateway with mod rewrite

### ISSUE THREAD

**Issue by pr4xx** [apereo/mod_auth_cas#129]
Hey there,
is it possible to make an exception for certain urls? I am using laravel (php framework) which uses mod rewrite for routing. The CASGateway directive seems to only allow directories to be ignored. I need somehing like "Allow url /this/is/a/path". Is this possible?

**Comment by dhawes** [comment]
I'm pretty sure CASGateway works on paths like this. Have you tried it?

Could you use different Locations with "AuthType CAS" and "AuthType None" in the proper places?

Feel free to post some config. I rarely use CASGateway, so it helps me to see some config to wrap my head around these examples.
