### ISSUE TITLE
When to support cas v3 Protocol？

### ISSUE THREAD

**Issue by cabbage89** [apereo/mod_auth_cas#133]
More and more applications, such as graylog, need to provide additional attributes when using CAS authentication.  [graylog cas auth](http://docs.graylog.org/en/2.3/pages/users_and_roles/external_auth.html#single-sign-on),
(eg:Email Header), and so on.

**Comment by dhawes** [comment]
What specifically do you need support for?

mod_auth_cas can do /samlValidate and add attributes to the HTTP headers now.

git master can do the same with CASv2 attributes.

We'll have to review CASv3 and see what we need to support, but I think you can probably do everything you need to do right now.

**Comment by cabbage89** [comment]
Adding attributes to an HTTP header must use saml, but CASv3 can also return attributes not only to saml, So i think it is necessary to support CASv3

**Comment by dhawes** [comment]
master supports CASv2 attributes, so I would expect that it will work with CASv3 as well since the payloads look the same.

I recommend you try it and report back.

**Comment by cabbage89** [comment]
CASAttributePrefix is valid when SAML validation is enabled. If I use CASv2, then no way to write attributes to the request header.

**Comment by dhawes** [comment]
Assuming git master, CASAttributePrefix is used for attributes returned with SAML validation **and** CASv2. Make sure to set CASAuthNHeader and attributes will be written to the request headers.

Have you tried testing this yet? If it doesn't work, post your Apache config, CAS response, and mod_auth_cas cache file and we'll go from there.

**Comment by cabbage89** [comment]
Thank you very much, hard you, I use the master branch compiler installation, everything is fine！！
