### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by ahai1980** [apereo/mod_auth_cas#137]
Hi,
i get the error
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
in httpd.conf
Alias /test "/var/www/html/test"
<Directory "/var/www/html/test">
Authtype CAS
require valid-user
Options Indexes MultiViews
AllowOverride all
Order allow,deny
Allow from all
thinks

**Comment by dhawes** [comment]
Set

LogLevel debug
CASDebug On

and look in your logs. You should have some indication of what's wrong. Copy them here if you need help.

**Comment by ahai1980** [comment]
[Wed Nov 22 20:54:41.089166 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(599): [client 172.16.0.187:53365] entering redirectRequest()
[Wed Nov 22 20:54:41.089172 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(611): [client 172.16.0.187:53365] Adding outgoing header: Location: https://sso.gettop.com/cas/login?service=http%3a%2f%2f168.88.28.20%2ftest%2f
[Wed Nov 22 20:54:41.296390 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Wed Nov 22 20:54:41.296408 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Wed Nov 22 20:54:41.296421 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(2076): [client 172.16.0.187:53365] Entering cas_authenticate()
[Wed Nov 22 20:54:41.296432 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(656): [client 172.16.0.187:53365] Modified r->args (now '')
[Wed Nov 22 20:54:41.296489 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1779): [client 172.16.0.187:53365] entering getResponseFromServer()
[Wed Nov 22 20:54:41.296617 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(584): [client 172.16.0.187:53365] CAS Service 'http%3a%2f%2f168.88.28.20%2ftest%2f'
[Wed Nov 22 20:54:46.362766 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1848): [client 172.16.0.187:53365] MOD_AUTH_CAS: curl_easy_perform() failed (Peer certificate cannot be authenticated with known CA certificates)
[Wed Nov 22 20:54:46.362802 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1440): [client 172.16.0.187:53365] entering isValidCASTicket()
^C
[admin@GD-BPM-SSO-PR2 logs]$ tail -200f test_error_log 
[Wed Nov 22 20:54:36.255314 2017] [auth_cas:debug] [pid 24088] mod_auth_cas.c(2601): entering check_vhost_config()
[Wed Nov 22 20:54:41.089017 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Wed Nov 22 20:54:41.089088 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Wed Nov 22 20:54:41.089115 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(2076): [client 172.16.0.187:53365] Entering cas_authenticate()
[Wed Nov 22 20:54:41.089148 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(584): [client 172.16.0.187:53365] CAS Service 'http%3a%2f%2f168.88.28.20%2ftest%2f'
[Wed Nov 22 20:54:41.089154 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(532): [client 172.16.0.187:53365] entering getCASLoginURL()
[Wed Nov 22 20:54:41.089162 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(509): [client 172.16.0.187:53365] entering getCASGateway()
[Wed Nov 22 20:54:41.089166 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(599): [client 172.16.0.187:53365] entering redirectRequest()
[Wed Nov 22 20:54:41.089172 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(611): [client 172.16.0.187:53365] Adding outgoing header: Location: https://sso.gettop.com/cas/login?service=http%3a%2f%2f168.88.28.20%2ftest%2f
[Wed Nov 22 20:54:41.296390 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Wed Nov 22 20:54:41.296408 2017] [authz_core:debug] [pid 2998] mod_authz_core.c(809): [client 172.16.0.187:53365] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Wed Nov 22 20:54:41.296421 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(2076): [client 172.16.0.187:53365] Entering cas_authenticate()
[Wed Nov 22 20:54:41.296432 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(656): [client 172.16.0.187:53365] Modified r->args (now '')
[Wed Nov 22 20:54:41.296489 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1779): [client 172.16.0.187:53365] entering getResponseFromServer()
[Wed Nov 22 20:54:41.296617 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(584): [client 172.16.0.187:53365] CAS Service 'http%3a%2f%2f168.88.28.20%2ftest%2f'
[Wed Nov 22 20:54:46.362766 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1848): [client 172.16.0.187:53365] MOD_AUTH_CAS: curl_easy_perform() failed (Peer certificate cannot be authenticated with known CA certificates)
[Wed Nov 22 20:54:46.362802 2017] [auth_cas:debug] [pid 2998] mod_auth_cas.c(1440): [client 172.16.0.187:53365] entering isValidCASTicket()

thanks!

**Comment by ahai1980** [comment]
i set CASCertificatePath 
and sucess
thanks!

**Comment by ruslanashaari** [comment]
hi @ahai1980 

how to set CASCertificatePath?

i'm a beginner in using CAS. please help
