### ISSUE TITLE
SameSite cookie attribute

### ISSUE THREAD

**Issue by pauljarc** [apereo/mod_auth_cas#140]
Are there any plans to add [the SameSite attribute](http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/#same-site-cookie-attribute) on authentication cookies?  Note that [section 5.2](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-5.2) of [the draft RFC](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00) suggests setting two cookies, one strict and one lax/unrestricted.  Web sites can then check for the strict cookie before performing any risky operations.  setCASCookie() could set both cookies, and cas_authenticate() could check a configuration option to choose which cookie name to pass to getCASCookie().  That configuration option could be set in .htaccess based on the requested URL, method, etc., so that web application code wouldn't need any modification.

**Comment by dhawes** [comment]
There are no plans that I'm aware of, but it would be simple enough to add, and I can see the benefit.

I'm not convinced the email example in the RFC is really that much of a concern here. If you had a strict cookie set and then went to a site that was protected by mod_auth_cas, you'd just get redirected to your CAS server and come back with a new cookie. But there probably are cases where this is useful, and allowing users to choose that behavior seems like a good thing.

**Comment by dhawes** [comment]
Fixed in https://github.com/apereo/mod_auth_cas/pull/190
