### ISSUE TITLE
CASCookiePath accepts only subdirs of /

### ISSUE THREAD

**Issue by Pilot001** [apereo/mod_auth_cas#141]
Environment:
Release: mod_auth_cas_1.1
OS: SLES 12 SP3
Apache: 2.4.23

After successfully building the module from source, I got an error when starting Apache saying:
MOD_AUTH_CAS: CASCookiePath '/tmp/cas/' is not a directory or does not end in a trailing '/'!

I tracked it down to mod_auth_cas.c line 300, where the comparison
   f.filetype != APR_DIR
fails. Interesting is that the content of "f.filetype" seems to be identical to strlen(value)!?
In my case: 9 != 2

Later I found that it works, if I reduce the path to a direct subdir of / (e.g. /tmp/ or /cas/), so I do have a workaround, but that should become fixed.

**Comment by Pilot001** [comment]
Re-tested with SLES11 SP4 and Apache 2.2.34: Here it works, so this seems to be an issue with Apache 2.4.

**Comment by dhawes** [comment]
Do you actually have a /tmp/cas/ directory? The error you get is what I'd expect if you don't. Create the directory and try again.

I have no issues on 2.4 when the directory exists.

**Comment by pekkarinenv** [comment]
I have the same problem with RHEL 7.4 and Apache 2.4.6. CASCookiePath must be /cas/, /tmp/, etc. Longer paths (/tmp/cas/, or /var/tmp/cas/) do not work at all. I agree that the content of "f.filetype" seems to be identical to strlen(value).

**Comment by dhawes** [comment]
I looked at this a little closer and it looks like the way we are using apr_stat() needs improvement. In particular, if stat() returns a nonzero value, the apr_finfo_t struct isn't populated, so f.filetype won't be correct.

That said, I cannot replicate this when the directories in question exist. Are you positive you can ls or stat the directory specified by CASCookiePath?

**Comment by pekkarinenv** [comment]
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: Starting The Apache HTTP Server...
Feb 26 10:22:14 DEVLABSOL000104 httpd[63797]: AH00526: Syntax error on line 6 of /etc/httpd/conf.d/auth_cas.conf:
Feb 26 10:22:14 DEVLABSOL000104 httpd[63797]: MOD_AUTH_CAS: CASCookiePath '/var/tmp/cas/' is not a directory or does not end in a trailing '/'!
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Feb 26 10:22:14 DEVLABSOL000104 kill[63799]: kill: cannot find process ""
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: httpd.service: control process exited, code=exited status=1
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: Failed to start The Apache HTTP Server.
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: Unit httpd.service entered failed state.
Feb 26 10:22:14 DEVLABSOL000104 systemd[1]: httpd.service failed.

[root@DEVLABSOL000104 ~]# grep CASCookie /etc/httpd/conf.d/auth_cas.conf
CASCookiePath /var/tmp/cas/

[root@DEVLABSOL000104 ~]# ls -ld /var/tmp/cas/
drwxrwxrwx 2 apache apache 6 Feb 24 18:28 /var/tmp/cas/
[root@DEVLABSOL000104 ~]# stat /var/tmp/cas
  File: ΓÇÿ/var/tmp/casΓÇÖ
  Size: 6               Blocks: 0          IO Block: 4096   directory
Device: f900h/63744d    Inode: 203356132   Links: 2
Access: (0777/drwxrwxrwx)  Uid: (   48/  apache)   Gid: (   48/  apache)
Access: 2018-02-26 10:21:08.099813100 +0200
Modify: 2018-02-24 18:28:46.922813100 +0200
Change: 2018-02-24 18:28:46.922813100 +0200
 Birth: -

**Comment by dhawes** [comment]
Are you using SELinux? If so, is the security context of your /cas directory the same as the security context of /var/tmp/cas?

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/sect-managing_confined_services-the_apache_http_server-types

**Comment by pekkarinenv** [comment]
No, I am not using SELinux.

[root@DEVLABSOL000104 ~]# ls -dZ /cas
drwxrwxr-x apache apache ?                                /cas
[root@DEVLABSOL000104 ~]# ls -dZ /var/tmp/cas
drwxrwxrwx apache apache ?                                /var/tmp/cas
[root@DEVLABSOL000104 ~]# getenforce
Disabled

**Comment by dhawes** [comment]
I cannot reproduce this with RHEL 7.4, Apache 2.4.6, and mod_auth_cas git master.

With SELinux enabled, I do have to use chcon to set httpd_sys_rw_content_t for the cookie directory, but otherwise everything works as expected.

Make sure all your directories are writable by the apache user.

**Comment by Ay4shi** [comment]
I solved my problem by relocating the CookiePath : 

mkdir /var/lib/cas
chown apache:apache /var/lib/cas
chmod 750 /var/lib/cas

And moving the library configuration outside of any VHost.

**Comment by ryerbanga** [comment]
Thanks. It works for me with the same recipe 
 Server version: Apache/2.4.6 (CentOS)
 Server built:   Jun 27 2018 13:48:59

**Comment by dhawes** [comment]
I was never able to reproduce this. Please reopen if you can provide explicit instructions on how to reproduce.
