### ISSUE TITLE
Add response header during 302 redirect to CAS server?

### ISSUE THREAD

**Issue by jwhitene** [apereo/mod_auth_cas#142]
Using Apache 2.4/mod_auth_cas, I can't find a way to issue an access-allow-control-origin header during the 302 redirect to the cas server.  

I've put Header set "Access-Control-Allow-Origin" "*" everywhere I can think of, and Apache just won't set it.   It is like the mod_auth_cas is 302 redirecting the the CAS server and ignoring all other configuration.  

I've put the 'Header set' line in mod_auth_cas at the top of the file, in the <location block, in httpd.conf before the modules are even loaded, in the top of ssl.conf, etc.

**Comment by dhawes** [comment]
You can use "always" to get the header to be set:

Header always set "Access-Control-Allow-Origin" "*"

Note that this header goes to your client, which is most likely a web browser. I don't think browsers will relay the header to the CAS server, which if I'm understanding is what you'd like to do.

**Comment by jwhitene** [comment]
I'll try 'always set' tomorrow.  In the meantime, we decided to do server side processing of the content we want, rather than using mod_proxy+mod_auth_cas.

It is not a matter of relaying the header, the sequence is like this:

User who has a CAS session already, requests a html page.  

In that page, is a .GET jquery call to apache+mod_proxy+mod_auth_cas.    The response from the server is a 302 redirect to the CAS server, without any of the custom header values or origin-allow type header values, that my apache is configured to send.  

If I remove mod_auth_cas, the browser can successfully make the call to the proxy server, because the server correctly sends the CORS related headers (Header set or Header add). If "always set" will force mod_auth_cas to issue my headers along with the 302 to the client, that would work for us.

**Comment by dhawes** [comment]
Thanks for the extra context, that makes sense.

I hope that "always set" works for your case. If not, we can devise something that will.
