### ISSUE TITLE
requirement of must installed libs have a little mistake

### ISSUE THREAD

**Issue by yxq477** [apereo/mod_auth_cas#143]
sorry for my poor English

> * libcurl - 7.18.2 or higher  

when i found the error of my libcurl not found ,i checked by `apt install ` i found libcurl is already installed. 
finally i found that i have to install libcurl4-gnutls-dev(or openssl/nss flavour) by`sudo apt install libcurl4-gnutls-dev`(or ...) and then the problem solved  

so. i think the guide of this have a little wrong.

**Comment by dhawes** [comment]
The README says:

```
The following development libraries and utilities must be installed:
* OpenSSL - 0.9.8c or higher
* Apache Portable Runtime - 1.2.8 or higher
* Apache Portable Runtime Utilities - 1.2.7 or higher
* Apache Web Server - 2.2.3 or higher
* libcurl - 7.18.2 or higher
* libpcre - 7.8 or higher
```
I think the guide is clear that you need the development libraries installed, which in your case was libcurl4-gnutls-dev.
