### ISSUE TITLE
mod_auth_cas strip "ticket=ST-" from URL used for GLPI using CAS authentication

### ISSUE THREAD

**Issue by saviosampaio** [apereo/mod_auth_cas#144]
GLPI already uses CAS authentication.

In the meantime, we would like to "protect" the GLPI URLs using mod_auth_cas.

However, after a user authenticates to "mod_auth_cas", we verify that "mod_auth_cas" is removing (strip) the "ticket = ST-" parameter from the URL that is sent by the user to the GLPI page "/front/login.php".

This causes the user's browser to enter a redirect's LOOP, generating new tickets, which are always striped from the URL by "mod_auth_cas".

Is there any parameter to prevent mod_auth_cas from removing this attribute from the URL?

This attribute is necessary so that the GLPI can receive it and can validate the user's ticket in CAS Host.

Thank you very much.

**Comment by saviosampaio** [comment]
I think that this approach can solve the problem:

```c
        // only remove parameters if a ticket was found (makes no sense to do this otherwise)
        /* start of new code approach */
        if((ticket != NULL)&&(cookieString != NULL)&&(isValidCASCookie(r, c, cookieString, &remoteUser, &attrs))){
                r->user = remoteUser;
                if(d->CASAuthNHeader != NULL)
                        apr_table_set(r->headers_in, d->CASAuthNHeader, remoteUser);
                return OK;
        }
        /* end of new code approach */
        if(ticket != NULL){
                parametersRemoved = removeCASParams(r);
        }
```

**Comment by dhawes** [comment]
I would expect this to work for your use case, but I'd have to look a little closer and test to make sure there aren't any odd side effects. For one, it looks like CAS attributes won't be set.

 Would it make sense to add a directive to enable this behavior? I'll have to think on that as well.

**Comment by saviosampaio** [comment]
Hi dhawes,

This is working for my use case.

The mod_auth_cas when see that user have a valid CAS Cookie, dont strip the "ticket=ST-" parameter, and now correctly redirects the user to GLPI or another system that also needs another CAS authentication.

This only occur after first authentication, what is made by mod_auth_cas.

One really needs to examine if there are any side effects.

It took us a while to understand the cause of the LOOP, when "mod_auth_cas" removed the "ticket" that another application was waiting to receive.

I wish that other users can analyze and contribute.

Many thanks and hugs!

**Comment by dhawes** [comment]
I understand the reasoning, but I do wonder if using some kind of HTTP authentication is better here. Something like: 

https://wordpress.org/plugins/http-authentication/

That said, I do see how this is useful. It seems proper to use a configuration directive to turn this on, and I'd like to see some analysis that considers adding CAS attributes. I encourage you to submit a pull request if you'd like to go that route.

**Comment by tsteiner** [comment]
I've come across this issues as well.  I've written a workaround that causes mod_auth_cas to specify a virtual service path of "/jasig/mod-auth-cas".  It will only ever attempt to process tickets at this address and leaves any other CAS services on the same server alone.

The code is in my fork at https://github.com/tsteiner/mod_auth_cas/tree/service-url

**Comment by dhawes** [comment]
@saviosampaio Can you test #158 for your use case?

**Comment by dhawes** [comment]
CASPreserveTicket from #158 should allow this. Reopen this issue if it doesn't.
