### ISSUE TITLE
How to build on Solaris?

### ISSUE THREAD

**Issue by tdb85** [apereo/mod_auth_cas#147]
I've downloaded 1.1.tar.gz from the Releases page and extracted.

<code>./configure</code> Seems to be ok, but <code>make</code> bails super quickly.  I've got installed SolarisStudio 12.4  which is in my PATH (/opt/solarisstudio12.4/bin) which contains the cc command.

I have gcc installed as well but not sure if I can tell make to use that instead, or if it would be successful.

I've included the command output, if that's helpful.
[mod_auth_cas_build_output.txt](https://github.com/apereo/mod_auth_cas/files/1926411/mod_auth_cas_build_output.txt)

**Comment by tdb85** [comment]
It's worth noting I downloaded the previous release, 1.0.9.1 compiles without a hitch but I'm having trouble getting it to validate the ticket.   It redirects to CAS but it ends up in redirect loop.  Other applications are doing CAS OK.

I forgot to add: I'm using Solaris 11.2 on SPARC, with Apache 2.2 from IPS.  I've also installed Solaris Developer Studio 12.5 with the same problem. 

Lastly, my CAS server does work with Apache on Linux x86-64 on CentOS 7 but that's a precompiled package.

I am going to take a stab at using mod_auth_mellon but I'm less familiar with SAML.

**Comment by dhawes** [comment]
I don't have a Solaris machine to test this on, but I'll look into getting one.

I'd be interested if you had any luck using gcc.

**Comment by tdb85** [comment]
I got mod_auth_cas running in my environment by taking a time machine back to 1.0.9.1 successfully.  I’m happy to contribute in any way I can but for now this meets our needs. It’s likely this will be our last Solaris based web server as they are all Linux now.
