### ISSUE TITLE
Session invalid after idle time less than what is defined.

### ISSUE THREAD

**Issue by MattAtTTU** [apereo/mod_auth_cas#151]
We have a complex configuration which includes Apache 2.4 running mod_auth_cas-1.1.3.  The web server is protected with CAS and once a user authenticated, the REMOTE_USER header is passed on to another application which actually authenticates the user and provisions roles, etc.  

We have our times set as follows in auth_cas.conf:

`CASIdleTimeout 7200`
`CASTimeout 28800`

When a user logs in and authenticates, we see the user's IP address and username in the access logs as we should.  However, after the user sits idle for a period around one hour, the sessions becomes invalid and causes the application to function improperly.  We do see CAS redirects in header captures which is why we're sure it's an invalid session. 

My question is why do we see timeouts after one hour when all timeouts that we know of (application, CAS and mod_auth_cas) are configured for at least two hours?  Have we missed something?  Any help would be greatly appreciated. 

Here is an example of the access log when we first login to the application without sitting idle:

`10.10.10.10 - username [14/Aug/2018:14:53:32 -0500]`

Here is an example after being idle for one hour and trying to make another request:

`10.10.10.10 - - [14/Aug/2018:16:18:55 -0500]`

Also, I've enabled debugging for the virtual host and mod_auth_cas module and no additional information is present in the logs, at least that I can find.

**Comment by dhawes** [comment]
Make sure that you have both "LogLevel debug" and "CASDebug On" in your config.

The logs should give us some insight into what is going on.

**Comment by MattAtTTU** [comment]
I have LogLevel debug in the virtual host config and CASDebug On in the auth_cas.conf. Is that what you’re referring to? If so, I’d be happy to share some of the logs. I haven’t seen anything jump out at me.

Matt Thompson
Assistant Managing Director
TOSM Enterprise Systems
Texas Tech University System
(806) 834-3646
________________________________

**Comment by MattAtTTU** [comment]
I think this is the logging information pertinent to the issue.  The error about the cache not being able to be opened and the cookie being invalid looks interesting to me.  What do you think?

```[Wed Aug 15 14:46:23.534944 2018] [ssl:info] [pid 7015] [client 10.10.10.10:54667] AH01964: Connection to child 29 established (server url.domain.com:443)
[Wed Aug 15 14:46:23.535244 2018] [socache_shmcb:debug] [pid 7015] mod_socache_shmcb.c(522): AH00835: socache_shmcb_retrieve (0x51 -> subcache 17)
[Wed Aug 15 14:46:23.535256 2018] [socache_shmcb:debug] [pid 7015] mod_socache_shmcb.c(877): AH00851: shmcb_subcache_retrieve found no match
[Wed Aug 15 14:46:23.535259 2018] [socache_shmcb:debug] [pid 7015] mod_socache_shmcb.c(532): AH00836: leaving socache_shmcb_retrieve successfully
[Wed Aug 15 14:46:23.535279 2018] [ssl:debug] [pid 7015] ssl_engine_kernel.c(1890): [client 10.10.10.10:54667] AH02043: SSL virtual host for servername url.domain.com found
[Wed Aug 15 14:46:23.552102 2018] [ssl:debug] [pid 7015] ssl_engine_kernel.c(1823): [client 10.10.10.10:54667] AH02041: Protocol: TLSv1, Cipher: ECDHE-RSA-AES128-SHA (128/128 bits)
[Wed Aug 15 14:46:23.553017 2018] [ssl:debug] [pid 7015] ssl_engine_kernel.c(225): [client 10.10.10.10:54667] AH02034: Initial (No.1) HTTPS request received for child 29 (server url.domain.com:443), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553097 2018] [authz_core:debug] [pid 7015] mod_authz_core.c(809): [client 10.10.10.10:54667] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553101 2018] [authz_core:debug] [pid 7015] mod_authz_core.c(809): [client 10.10.10.10:54667] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553107 2018] [:debug] [pid 7015] mod_auth_cas.c(2058): [client 10.10.10.10:54667] Entering cas_authenticate(), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553122 2018] [:debug] [pid 7015] mod_auth_cas.c(1655): [client 10.10.10.10:54667] entering isValidCASCookie(), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553124 2018] [:debug] [pid 7015] mod_auth_cas.c(892): [client 10.10.10.10:54667] entering readCASCacheFile(), referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553161 2018] [:debug] [pid 7015] mod_auth_cas.c(926): [client 10.10.10.10:54667] Cache entry '9f14614c6332e1ea9980d693885324aa' could not be opened, referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome
[Wed Aug 15 14:46:23.553163 2018] [:debug] [pid 7015] mod_auth_cas.c(1660): [client 10.10.10.10:54667] Cookie '9f14614c6332e1ea9980d693885324aa' is corrupt or invalid, referer: https://url.domain.com/ibmcognos/bi/?perspective=Welcome

**Comment by MattAtTTU** [comment]
This looks like what we're seeing.  I can confirm Ajax calls are involved on our end.  We're running the prefork MPM with Apache 2.4.  I'm wondering if changing to Worker or Event would help.  

https://groups.google.com/forum/#!topic/jasig-cas-user/zcngEDnWIUE

**Comment by dhawes** [comment]
Those errors could simply mean that the 9f14614c6332e1ea9980d693885324aa cookie file was deleted. Do you see any other reference to 9f14614c6332e1ea9980d693885324aa in the log file?

Does the file 9f14614c6332e1ea9980d693885324aa exist in your CASCookiePath?

**Comment by dhawes** [comment]
You should see debug output when the cookie was created and when it was removed.

Try your test again and verify that your cookie file exists and is readable. If mod_auth_cas removes the file, you should see it in the logs.

**Comment by dhawes** [comment]
I wouldn't expect a difference, but the LB does raise some questions.

Do you have multiple Apache nodes behind the LB? If so, are you using sticky sessions, and what is the timeout for these sessions?

**Comment by MattAtTTU** [comment]
Yes, we have multiple nodes (two to be exact).  We do use session persistence based on client IP and I can confirm that the sessions are sticking to the web server they initially hit.  The timeout is set at two hours so this issue is occurring prior to that happening.

**Comment by MattAtTTU** [comment]
Late on Friday, we redirected the main URL for the application directly to the web node on port 443.  Since we were unable to reproduce the issue directly against 443 but could reproduce through the load balancer, we wanted to force all users directly to the web node.  Unfortunately, we can now reproduce the issue directly against the web node on port 443.  That has lead us to think the issue may be due to user load.  Would the cookie cache be cleaned up based on size at some point?

**Comment by dhawes** [comment]
The cache is cleaned based on time. See CASCacheCleanInterval, which defaults to 30m.

When the cache is cleaned, you should see delete messages in your debug logs.

Let's be methodical.

1. Login to your application.
2. Note the cookie in your web browser.
3. Verify that this file exits in your CASCookiePath.
4. Wait for your CASIdleTimeout.
5. Hit your application again.
6. grep your debug logs for the cookie. Post them here.
7. Does the file still exist in your CASCookiePath?

**Comment by MattAtTTU** [comment]
I have logged into the application, noted my cookie ID and verified it is in the path.  My timeout is set at two hours.  This typically happens after only one.  I will try again in an hour or so and see if the issue occurs.  If so, I will post cookie results and debug logs, if available.

**Comment by MattAtTTU** [comment]
After just over one hour, the timeout issue occurred.  The cookie ID was the same in the browser but did not exist in the cache on the web server once the issue presented. 

The apache error log with debug enabled has the following entries for the cookie.  

```[Mon Aug 20 17:15:48.399887 2018] [auth_cas:debug] [pid 23912:tid 139825394996992] mod_auth_cas.c(1298): [client 10.10.10.10:58895] Cookie '8610f7d74075e007cb21792313450e42' created for user 'username', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a15%3a42Z
[Mon Aug 20 17:15:48.399964 2018] [auth_cas:debug] [pid 23912:tid 139825394996992] mod_auth_cas.c(811): [client 10.10.10.10:58895] Adding outgoing header: Set-Cookie: MOD_AUTH_CAS_S=8610f7d74075e007cb21792313450e42;Secure;Path=/; HttpOnly, referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a15%3a42Z
[Mon Aug 20 17:40:44.101345 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(1146): [client 100.43.57.27:63249] Processing cache file '8610f7d74075e007cb21792313450e42', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
[Mon Aug 20 17:40:44.101358 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(930): [client 100.43.57.27:63249] Cache entry '8610f7d74075e007cb21792313450e42' could not be opened, referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
[Mon Aug 20 17:40:44.101364 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(1162): [client 100.43.57.27:63249] Removing corrupt cache entry '8610f7d74075e007cb21792313450e42', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
[Mon Aug 20 18:23:27.615467 2018] [auth_cas:debug] [pid 23913:tid 139825243928320] mod_auth_cas.c(930): [client 10.10.10.10:62497] Cache entry '8610f7d74075e007cb21792313450e42' could not be opened, referer: https://cognos.domain.com/ibmcognos/bi/?perspective=InstanceWelcome
[Mon Aug 20 18:23:27.615470 2018] [auth_cas:debug] [pid 23913:tid 139825243928320] mod_auth_cas.c(1676): [client 10.10.10.10:62497] Cookie '8610f7d74075e007cb21792313450e42' is corrupt or invalid, referer: https://cognos.domain.com/ibmcognos/bi/?perspective=InstanceWelcome
```
Note that username, IP address and domain names have been changed for security reasons.  Also, note that there are two domains in use.  The application resides as domain.com while the federation services CAS calls reside at domain2.com.  I don't think that's the issue because this issue doesn't always occur.  I just wanted to point that out.

**Comment by MattAtTTU** [comment]
This appears to be where the issue occurs.  The first request looks good and is accepted but the second is denied and the CAS redirect happens.  I'm unsure why it behaves this way. 

```[Mon Aug 20 17:15:41.081291 2018] [ssl:info] [pid 23968:tid 139825327855360] [client 10.10.10.10:58879] AH01964: Connection to child 206 established (server cognos.domain.com:443)
[Mon Aug 20 17:15:41.081473 2018] [ssl:debug] [pid 23968:tid 139825327855360] ssl_engine_kernel.c(1890): [client 10.10.10.10:58879] AH02043: SSL virtual host for servername cognos.domain.com found
[Mon Aug 20 17:15:41.087477 2018] [ssl:debug] [pid 23968:tid 139825327855360] ssl_engine_kernel.c(1823): [client 10.10.10.10:58879] AH02041: Protocol: TLSv1, Cipher: ECDHE-RSA-AES128-SHA (128/128 bits)
[Mon Aug 20 17:15:41.089727 2018] [ssl:debug] [pid 23968:tid 139825327855360] ssl_engine_kernel.c(225): [client 10.10.10.10:58879] AH02034: Initial (No.1) HTTPS request received for child 206 (server cognos.domain.com:443)
[Mon Aug 20 17:15:41.089797 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of Require all granted: granted
[Mon Aug 20 17:15:41.089800 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of <RequireAny>: granted
[Mon Aug 20 17:15:41.089828 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of Require all granted: granted
[Mon Aug 20 17:15:41.089832 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of <RequireAny>: granted
[Mon Aug 20 17:15:41.388405 2018] [ssl:debug] [pid 23968:tid 139825327855360] ssl_engine_kernel.c(225): [client 10.10.10.10:58879] AH02034: Subsequent (No.2) HTTPS request received for child 206 (server cognos.domain.com:443)
[Mon Aug 20 17:15:41.388519 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Mon Aug 20 17:15:41.388524 2018] [authz_core:debug] [pid 23968:tid 139825327855360] mod_authz_core.c(809): [client 10.10.10.10:58879] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Mon Aug 20 17:15:41.388532 2018] [auth_cas:debug] [pid 23968:tid 139825327855360] mod_auth_cas.c(2076): [client 10.10.10.10:58879] Entering cas_authenticate()
[Mon Aug 20 17:15:41.388548 2018] [auth_cas:debug] [pid 23968:tid 139825327855360] mod_auth_cas.c(584): [client 10.10.10.10:58879] CAS Service 'https%3a%2f%2fcognos.domain.com%2fibmcognos'
[Mon Aug 20 17:15:41.388552 2018] [auth_cas:debug] [pid 23968:tid 139825327855360] mod_auth_cas.c(532): [client 10.10.10.10:58879] entering getCASLoginURL()
[Mon Aug 20 17:15:41.388557 2018] [auth_cas:debug] [pid 23968:tid 139825327855360] mod_auth_cas.c(509): [client 10.10.10.10:58879] entering getCASGateway()
[Mon Aug 20 17:15:41.388560 2018] [auth_cas:debug] [pid 23968:tid 139825327855360] mod_auth_cas.c(599): [client 10.10.10.10:58879] entering redirectRequest()

**Comment by dhawes** [comment]
This line is interesting:

`
[Mon Aug 20 17:40:44.101364 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(1162): [client 100.43.57.27:63249] Removing corrupt cache entry '8610f7d74075e007cb21792313450e42', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
`

Presumably CASCleanCache() is called, the file is found in the cache directory, and then the file can't be read. When you open the file, does it look valid? Do file permissions look right? Does the file change before the cache is cleaned?

Can you post your Apache config?

**Comment by MattAtTTU** [comment]
The file has never been there after I receive the error so could not be opened.  I was going to attempt to open it before reproducing the error today but early testing indicates that setting the CASCacheCleanInterval to 3 hours (timeout is configured at 2) has possibly resolved the issue.  I had a session which sat idle for over an hour and was still able to access the site.  This has not worked before.  Also, my cookie was still present and unchanged in the cache.  I will update with the results of further testing but it does seem like the CASCacheCleanInterval isn't as trivial as the documentation indicates. 

`CASCacheCleanInterval 10800`

**Comment by dhawes** [comment]
What other mod_auth_cas logs are there around these times?

```
[Mon Aug 20 17:40:44.101345 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(1146): [client 100.43.57.27:63249] Processing cache file '8610f7d74075e007cb21792313450e42', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
[Mon Aug 20 17:40:44.101358 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(930): [client 100.43.57.27:63249] Cache entry '8610f7d74075e007cb21792313450e42' could not be opened, referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
[Mon Aug 20 17:40:44.101364 2018] [auth_cas:debug] [pid 23913:tid 139825509398272] mod_auth_cas.c(1162): [client 100.43.57.27:63249] Removing corrupt cache entry '8610f7d74075e007cb21792313450e42', referer: https://fs.domain.com/adfs/ls/wia?wa=wsignin1.0&wtrealm=https%3a%2f%2fauth.domain.com%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fsignin.aspx%253fredirect%253dhttps%25253A%25252F%25252Fcas.domain.com%25252Fsso3.4%25253FredirectUrl%25253D%2525252Fsso3.4%2525252Flogin%2525253Fservice%2525253Dhttps%252525253a%252525252f%252525252fcognos.domain.com%252525252fibmcognos&wct=2018-08-20T22%3a40%3a34Z
```

I've been unable to reproduce this, so the more information about how the cache is getting corrupt (or removed) is useful. Periodically inspecting the cache file may tell us something about what is going on.

**Comment by MDeeApp** [comment]
Any news on this issue? I'm hitting nearly the same errors.

**Comment by dhawes** [comment]
If you can provide logs and a detailed account of what's going on with your cache, that would be helpful in determining what the issue is.

Better yet, if you can provide a way to reliably reproduce this issue with configuration details, that would be great. I still have been unable to reproduce this.

**Comment by MattAtTTU** [comment]
Sorry to leave this hanging.  I've actually changed jobs and am no longer working on this issue.  We ended up working away from mod_auth_cas to a vendor supported method anyway so not sure we would have been able to troubleshoot.  I think this can be closed.
