### ISSUE TITLE
Securing root and subfolder differently

### ISSUE THREAD

**Issue by Ay4shi** [apereo/mod_auth_cas#154]
Hi,

I have an issue with the following configuration :
```

 <Location "/Produits/baomdpldap">
  AddDefaultCharset Off
  AuthType CAS
  AuthName "MyCompany CAS"
  <RequireAny>
   Require valid-user
  </RequireAny>
 </Location>

 <Location "/">
  AuthType CAS
  AuthName "MyCompany CAS"
  AuthLDAPURL ldap://xxx
  AuthLDAPBindDN "xxx"
  AuthLDAPBindPassword "xxx"
  <RequireAny>
   Require ldap-attribute appli="intra_utili"
  </RequireAny>
 </Location>
```

Permissions at the root are most aggressive as we authenticate and authorize with LDAP. This is working as expected.

Permissions at the "/Produits/baomdpldap" only require a valid user.

When I try to access the "/Produits/baomdpldap" folder, the LDAP check is always performed. I've tried the CASRenew directive but it does nothing.

Any help would be appreciated.

**Comment by dhawes** [comment]
What happens if you switch the Location order?
