### ISSUE TITLE
Invalid command 'CASAllowWildcardCert'

### ISSUE THREAD

**Issue by cremos** [apereo/mod_auth_cas#167]
Hello,
I just upgrade a 16.04 ubuntu to ubuntu 18.04. libapache2-mod-auth-case 1.1-2.1ubuntu1 module error when starting apache: Invalid command 'CASAllowWildcardCert', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
I did not find anything about this error.
Have you ever had type of error?
thank you in advance for your return.
Crémos

**Comment by cremos** [comment]
I am in Apache 2.4.7-1ubuntu4.21
I did not see anything in the documentation: https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252587/mod+auth+cas
Crémos

**Comment by dhawes** [comment]
CASAllowWildcardCert was removed in 2014 when mod_auth_cas started using libcurl.

You should remove this directive from your config.
