### ISSUE TITLE
Evaluate expressions in Require cas-attribute

### ISSUE THREAD

**Issue by drsimmo** [apereo/mod_auth_cas#168]
Hi,

I'm trying to use expressions to use a name from a URL to authorise a group attribute returned by my CAS server. My mod_auth_cas config is below:

`  	CASCookiePath /var/cache/apache2/mod_auth_cas/
	CASLoginURL https://example.com/cas/login
	CASValidateURL https://example.com/cas/p3/serviceValidate
	CASDebug On
  
    <DirectoryMatch  "^/opt/teamdata/(?<sitename>[A-Za-z0-9]+)">
        Dav On
        LogMessage "--->%{env:MATCH_SITENAME}<----"
        define grp %{env:MATCH_SITENAME}
        LogMessage "***${grp}***"
        Options Indexes FollowSymLinks
	AuthType CAS

        <RequireAny>
            <RequireAll>
	      Require valid-user
              Require cas-attribute groups:cn=${grp},OU=Groups,OU=Accounts,DC=example,DC=com
                <Limit DELETE>
                   Require all denied
               </Limit>
            </RequireAll>
        </RequireAny>
`
At the moment ${grp} is being evaluated as %{env:MATCH_SITENAME}, but this expression is not being evaluated. The two LogMessage directives are to check that the server is evaluating everything correctly, which it is.

Does mod_auth_cas parse and evaluate expressions? Or is this expected behaviour? If the former, what am I doing wrong?

If I explicitly define the group, the Require cas-attribute groups:<value> works.

Thanks,
Simon

**Comment by dhawes** [comment]
mod_auth_cas does not parse and evaluate expressions, but it should be easy to add.

Try something like:

```
diff --git a/src/mod_auth_cas.c b/src/mod_auth_cas.c                                                   
index 9228e80..20bd4e4 100644
--- a/src/mod_auth_cas.c
+++ b/src/mod_auth_cas.c
@@ -2422,13 +2422,32 @@ authz_status cas_check_authorization(request_rec *r,
    const char *t, *w;
    unsigned int count_casattr = 0;
 
+    const ap_expr_info_t *expr = parsed_require_line;
+    const char *require;
+    const char *err = NULL;
+
    if(c->CASDebug)
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                  "Entering cas_check_authorization.");
 
    if(!r->user) return AUTHZ_DENIED_NO_USER;
 
-   t = require_line;
+    require = ap_expr_str_exec(r, expr, &err);
+    if (err) {
+        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, APLOGNO(02586)
+                      "cas_check_authorization: require cas-attribute: Can't evaluate expression: %s",
+                      err);
+        return AUTHZ_DENIED;
+    }
+
+    t = require;
+
+    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, APLOGNO(01713)
+                  "cas_check_authorization: require cas-attribute: testing for attr "
+                  "\"%s\"",
+                  t);
+
+
    while ((w = ap_getword_conf(r->pool, &t)) && w[0]) {
        count_casattr++;
        if (cas_match_attribute(w, attrs, r) == CAS_ATTR_MATCH) {
@@ -2451,10 +2470,29 @@ authz_status cas_check_authorization(request_rec *r,
    return AUTHZ_DENIED;
 }
 
+static const char *cas_parse_config(cmd_parms *cmd, const char *require_line,
+                                     const void **parsed_require_line)
+{
+    const char *expr_err = NULL;
+    ap_expr_info_t *expr;
+
+    expr = ap_expr_parse_cmd(cmd, require_line, AP_EXPR_FLAG_STRING_RESULT,
+            &expr_err, NULL);
+
+    if (expr_err)
+        return apr_pstrcat(cmd->temp_pool,
+                           "Cannot parse expression in require line: ",
+                           expr_err, NULL);
+
+    *parsed_require_line = expr;
+
+    return NULL;
+}
+
 static const authz_provider authz_cas_provider =
 {
    &cas_check_authorization,
-   NULL,
+   &cas_parse_config,
 };
 
 #else
```

**Comment by drsimmo** [comment]
Thanks for that.

I’ve come up with a slightly different solution that is working. I will put in a pull request shortly.

Thanks,
Simon

**Comment by dhawes** [comment]
Feel free to submit a PR.

**Comment by Milzor** [comment]
@drsimmo Im looking for exactly the same feature. Any chance to find some time for the PR?
