### ISSUE TITLE
CASCertificatePath doesn't work properly in apache chroot

### ISSUE THREAD

**Issue by sidrew** [apereo/mod_auth_cas#169]
I'm seeing some strange behavior with mod_auth_cas when configured in an apache chroot environment.  It seems like it can't read the path properly and gets generally confused.  For instance, if I set the path thusly..

CASCertificatePath /tmp/cert-chain.pem

Then the I get:

MOD_AUTH_CAS: Could not process Certificate Authority ...

So... since this site is configured in a chroot... if I recreate this path in my chroot jail:

/path/to/jail/tmp/cert-chain.pem

I get this error instead:

MOD_AUTH_CAS: curl_easy_perform() failed (Problem with the SSL CA cert (path? access rights?)) ... 

So... it kinda seems like it's trying to read the file in the jail... and despite permissions being set properly... it can't read the file in the jail.

**Comment by dhawes** [comment]
> MOD_AUTH_CAS: Could not process Certificate Authority ...

That's what I'd expect if apr_stat() did not think this was a directory or file.

You've tried running without chroot with the same chain file, right?

What OS is this? What SSL library is libcurl using? Can you use curl on the command line with the --cacert option against your CAS server successfully?

**Comment by sidrew** [comment]
On Tue, 2019-04-16 at 14:26 -0700, David Hawes wrote:
> > MOD_AUTH_CAS: Could not process Certificate Authority ...
> 
> That's what I'd expect if apr_stat() did not think this was a
> directory or file.
> You've tried running without chroot with the same chain file, right?

No... I've not... this is all part of an RHCS based cluster service...
reconfiguring this to turn off the chroot will be difficult.  I'll try
something in parallel.

> What OS is this?

This is a RHEL 6.10 system...

> What SSL library is libcurl using?

# curl -V
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1
zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp
sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

>  Can you use curl on the command line with the --cacert option
> against your CAS server successfully?

Yeah... that seems to work just fine.

**Comment by dhawes** [comment]
I see the following in the curl manpage:

```
              If curl is built against the NSS  SSL  library,  the  NSS  PEM  PKCS#11  module  (lib‐
              nsspem.so) needs to be available for this option to work properly.
```

Are

```
libnsspem.so
libsoftokn3.so
```

in your chroot jail?

**Comment by sidrew** [comment]
On Tue, 2019-04-16 at 16:35 -0700, David Hawes wrote:
> I see the following in the curl manpage:
>               If curl is built against the
> NSS  SSL  library,  the  NSS  PEM  PKCS#11  module  (lib‐
>               nsspem.so) needs to be available for this option to
> work properly.
> Are
> libnsspem.so
> libsoftokn3.so
> in your chroot jail?

Yup... they are already.  I was able to massage this site out of its
chroot jail for testing and get mod_auth_cas working... so, definitely
something is up.

Suggestions on tracing this further in the jail?

**Comment by dhawes** [comment]
I'd try to get curl working in the jail first before troubleshooting Apache and mod_auth_cas further. 

Alternatively, I'd try to use a curl package that uses OpenSSL.

**Comment by sidrew** [comment]
On Wed, 2019-04-17 at 13:52 +0000, David Hawes wrote:
> I'd try to get curl working in the jail first before troubleshooting
> Apache and mod_auth_cas further.
> Alternatively, I'd try to use a curl package that uses OpenSSL.

Okay... yeah... I was totally missing more than a couple of libraries. 
All fixed up.  She's working as expected.

Thanks!

**Comment by dhawes** [comment]
Excellent, glad it's working.
