### ISSUE TITLE
Unable to use cas-attribute directive apache > 2.4 

### ISSUE THREAD

**Issue by cremos** [apereo/mod_auth_cas#174]
Hello !

Has anyone been able to use the `mod_auth_cas` `require cas-attribute` directive to work with the `memberOf` or other multi-valued attribute?

Here is an excerpt from my configuration:
<RequireAny>
             Require valid-user
             Require cas-attribute groups:cn=${grp},OU=Groups,OU=Accounts,DC=example,DC=com
             Require all granted
</RequireAny>

After an apache2ctl configtest, I have the error below : 
**Unknown Authz provider: cas-attribute**
I installed the libapache2-mod-auth-case (1.0.9.1-4) module for apache 2.4.18 on an Ubuntu 16.04.6 LTS.
Have you ever encountered this type of error, thank you in advance for your answers.
Crémos

**Comment by dhawes** [comment]
require cas-attribute was added in mod_auth_cas v1.1. Try upgrading. If you still have issues enable debug logging and check your logs.

**Comment by cremos** [comment]
Hello !
Thanks for your responsiveness, I just upgraded from Ubuntu Linux 16.04 to 18.04 and upgraded to libapache2-mod-auth-1.1-2.1ubuntu1 case. The Require case-attribute directive <attribute>: <value> is now included in the apache2.4 configuration.

I have a new error:
Invalid command 'CASValidateServer', perhaps misspelled or defined by a module not included in the server configuration.

Crémos

**Comment by dhawes** [comment]
CASValidateServer was removed in v1.1. Here's the test from the old README:

https://github.com/apereo/mod_auth_cas/commit/1b1032c230a3ddf9db9004326bd4d075ab602c0e#diff-c47c7c7383225ab55ff591cb59c41e6b
