### ISSUE TITLE
always the same old problem

### ISSUE THREAD

**Issue by defaliz** [apereo/mod_auth_cas#175]
Hi, i don't know why but since 15 days i've always the same connexion problem
My apache2 page is well redirected to my cas login page,
authentication is granted with my CAS, as you i can see in logs (in the bottom of this messge)
but on my php page i have "ERR_EMPTY_RESPONSE" and a blank page.
last line in my log apache2 is : 

 _**mod_auth_cas.c(1830): [client 192.168.8.116:57021] entering getResponseFromServer(), referer: https://cas.inha.fr/cas/login?service=https%3a%2f%2fwebdav.inha.fr%2fad.php**_

it seems there is no response from the CAS to apache service ?

thanks for your help

logs in my CAS server
WHO: srogue
WHAT: TGT-79-********************************************************Nd6jBbPWwGYcastor
ACTION: TICKET_GRANTING_TICKET_CREATED
APPLICATION: CAS
WHEN: Tue Jul 16 16:50:31 CEST 2019
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1

**Comment by dhawes** [comment]
Please keep this discussion on #172.

**Comment by defaliz** [comment]
Hi  dhawes, why do you closed my post ?
i've still no answer and i can't use the module ? what's the problem
regards

**Comment by defaliz** [comment]
ok, sorry i've had not see your response : 
Please keep this discussion on #172.
