### ISSUE TITLE
VirtaualHost configuration for apache in a container

### ISSUE THREAD

**Issue by bhargaviaaa** [apereo/mod_auth_cas#180]
Please provide sample VirtualHost configuration for httpd in a container.

VirtualHost configuration which works for httpd without a container, does not work with httpd in a container.

**Comment by dhawes** [comment]
Can you be more specific about what doesn't work?

**Comment by bhargaviaaa** [comment]
I have below setting in httpd.conf:
<VirtualHost *:80>
		CASLoginURL https://sample.com/cas/login
		CASValidateURL https://sample.com/cas/serviceValidate
        CASCookiePath <path to directory>
        CASCertificatePath <path to certificate>
        CASVersion 2
        <Location  /otherWebPage>
            AuthType CAS
           Require valid-user
        </Location>
        ProxyPreserveHost On
        ProxyRequests Off
        ProxyPass /otherWebPage http://sample2.com/
        ProxyPassReverse /otherWebPage http://sample2.com/
</VirtualHost>

I get 403 error on providing valid credentials. In log file authentication response is not coming after the message 'entering isValidCASTicket()'. But on hitting /serviceValidate in browser by passing Service ticket, I can see the xml response which returns user name.

**Comment by dhawes** [comment]
Can you post your full VirtualHost config and Apache error log with "CASDebug On"?

**Comment by bhargaviaaa** [comment]
[Wed Nov 20 09:36:38.465778 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(557): [client y.y.y.y:61661] entering getCASLoginURL()
[Wed Nov 20 09:36:38.465785 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(534): [client y.y.y.y:61661] entering getCASGateway()
[Wed Nov 20 09:36:38.465802 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(624): [client y.y.y.y:61661] entering redirectRequest()
[Wed Nov 20 09:36:38.465811 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(636): [client y.y.y.y:61661] Adding outgoing header: Location: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:38.465923 2019] [headers:debug] [pid 27317] mod_headers.c(848): AH01503: headers: ap_headers_error_filter()
[Wed Nov 20 09:36:38.859229 2019] [proxy:debug] [pid 27654] proxy_util.c(1843): AH00925: initializing worker https://sample2:3001 shared
[Wed Nov 20 09:36:38.859340 2019] [proxy:debug] [pid 27654] proxy_util.c(1885): AH00927: initializing worker https://sample2:3001 local
[Wed Nov 20 09:36:38.859366 2019] [proxy:debug] [pid 27654] proxy_util.c(1936): AH00931: initialized single connection worker in child 27654 for (sample2)
[Wed Nov 20 09:36:47.044709 2019] [ssl:debug] [pid 27317] ssl_engine_kernel.c(225): [client y.y.y.y:61661] AH02034: Subsequent (No.2) HTTPS request received for child 0 (server sample1:448), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.044818 2019] [authz_core:debug] [pid 27317] mod_authz_core.c(809): [client y.y.y.y:61661] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.044826 2019] [authz_core:debug] [pid 27317] mod_authz_core.c(809): [client y.y.y.y:61661] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.044862 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(2150): [client y.y.y.y:61661] Entering cas_authenticate(), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.044874 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(681): [client y.y.y.y:61661] Modified r->args (now ''), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.045007 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(1828): [client y.y.y.y:61661] entering getResponseFromServer(), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.045186 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(609): [client y.y.y.y:61661] CAS Service 'https%3a%2f%2fx.x.x.x%3a443%2fsample2', referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.218997 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(1900): [client y.y.y.y:61661] MOD_AUTH_CAS: curl_easy_perform() failed (Peer's certificate issuer has been marked as not trusted by the user.), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.219096 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(1465): [client y.y.y.y:61661] entering isValidCASTicket(), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2
[Wed Nov 20 09:36:47.219130 2019] [headers:debug] [pid 27317] mod_headers.c(848): AH01503: headers: ap_headers_error_filter()
[Wed Nov 20 09:36:47.325975 2019] [ssl:debug] [pid 27317] ssl_engine_kernel.c(225): [client y.y.y.y:61661] AH02034: Subsequent (No.3) HTTPS request received for child 0 (server sample1:448)
[Wed Nov 20 09:36:47.326279 2019] [authz_core:debug] [pid 27317] mod_authz_core.c(835): [client y.y.y.y:61661] AH01628: authorization result: granted (no directives)
[Wed Nov 20 09:36:47.326407 2019] [headers:debug] [pid 27317] mod_headers.c(823): AH01502: headers: ap_headers_output_filter()
[Wed Nov 20 09:37:02.341750 2019] [ssl:info] [pid 27317] (70007)The timeout specified has expired: [client y.y.y.y:61661] AH01991: SSL input filter read failed.
[Wed Nov 20 09:37:02.341881 2019] [ssl:debug] [pid 27317] ssl_engine_io.c(993): [client y.y.y.y:61661] AH02001: Connection closed to child 0 with standard shutdown (server sample1:448)

**Comment by dhawes** [comment]
`[Wed Nov 20 09:36:47.218997 2019] [auth_cas:debug] [pid 27317] mod_auth_cas.c(1900): [client y.y.y.y:61661] MOD_AUTH_CAS: curl_easy_perform() failed (Peer's certificate issuer has been marked as not trusted by the user.), referer: https://x.x.x.x/cas/login?service=https%3a%2f%2fx.x.x.x%3a443%2fsample2`

It looks like you have a trust issue with your CAS server. Make sure you have the correct CA chain in CASCertificatePath.

**Comment by bhargaviaaa** [comment]
But on hitting same CAS service validate url in browser with service and ticket parameter gives me user name.

**Comment by dhawes** [comment]
Your browser trusts your CAS server certificate.

The problem here is that mod_auth_cas does not trust the CAS server certificate, so it cannot validate the ticket.

**Comment by bhargaviaaa** [comment]
Thank you!!!
Changed the certificate. Working fine now.

**Comment by dhawes** [comment]
Great, I'm glad it's working now.
