### ISSUE TITLE
Alternative nginx module like this?

### ISSUE THREAD

**Issue by liudonghua123** [apereo/mod_auth_cas#185]
Do we have any plans for `mod_auth_cas` for nginx alternatives?

**Comment by pames** [comment]
Maybe you are looking for https://github.com/bnoordhuis/ngx_http_auth_cas_module ?

@bnoordhuis FYI

**Comment by bnoordhuis** [comment]
I haven't updated that module after nginx 0.8 came out though. :-)

If someone wants to adopt it, you're welcome to it. I'm also open to sponsoring, although caveat emptor, I don't have much free time at the moment.

With sponsoring I mean a donation to a mutually acceptable charity proportional to the work involved.

**Comment by liudonghua123** [comment]
@bnoordhuis Yes, this project did not update almost 10 years. 😲 

I also see a similar project https://github.com/EsupPortail/nginx-auth-cas-lua, I will try to test with the latest cas and nginx. And maybe I will make some prs.
