### ISSUE TITLE
WARNING: 'aclocal-1.15' is missing on your system

### ISSUE THREAD

**Issue by burapasa** [apereo/mod_auth_cas#187]
hello 
i tried to install daq as you said with latest version but when i type "make" command it shows me following errors:
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:372: recipe for target 'aclocal.m4' failed
make: * [aclocal.m4] Error 127

**Comment by dhawes** [comment]
Try:

autoreconf -ivf

before the make.

**Comment by burapasa** [comment]
thank you david ,it worked
