### ISSUE TITLE
Repo epel on Centos 8 

### ISSUE THREAD

**Issue by wixaw** [apereo/mod_auth_cas#194]
Hello
When will the package be available on Centos 8?
Our policy is not to compile any packages, we cannot migrate our web servers without this dependency.
Thank you
William

**Comment by dhawes** [comment]
This project only supplies source code. Packages are maintained by distributions. I recommend you ask CentOS.

**Comment by wixaw** [comment]
ah ok i thought you ask to be there
Thanks

**Comment by vwbusguy** [comment]
You can use this for now until EPEL gets a proper update: https://copr.fedorainfracloud.org/coprs/vwbusguy/mod_auth_cas/

**Comment by vwbusguy** [comment]
Request to update it in EPEL: https://bugzilla.redhat.com/show_bug.cgi?id=1934268

**Comment by vwbusguy** [comment]
Hey there, it's back in EPEL now and supports EL7 through EL8 (and all current versions of Fedora).
