### ISSUE TITLE
Too many redirects - ticket validation to CASLoginURL

### ISSUE THREAD

**Issue by harishbabusmiles** [apereo/mod_auth_cas#196]
I have a difficult situation as below when using v1.1-3 mod_auth_cas in apache 2.4 and trying to authenticate with v3.5 cas-server. Unfortunately, I cannot upgrade the cas-server and had to work with this version.

Below is my CAS configuration for my vhost: https://myapp.domain.com

```
<IfModule mod_auth_cas.c>
        CASVersion 2
        CASCookiePath /var/cache/mod_cas/cookies/
        CASIdleTimeout 300
        CASTimeout 3600
        CASDebug On
        CASLoginURL https://mycas.domain.com/security/login
        CASValidateURL https://mycas.domain.com/security/serviceValidate
        CASCertificatePath /etc/httpd/conf/certs/mycas-domain.com-chain.pem

    <Location "/app1">
        CASScope /
        AuthType CAS
        require valid-user
    </Location>
</IfModule>
```

when I use my URL, I get redirected to the login page and when credentials are passed, I receive an ST ticket, but instead of validating the ticket using the CASValidateURL, the requests are getting redirected to CASLoginURL again with Service&Ticket parameters. And this gets repeated until too many redirects issue.

i.e instead of validating the ticket with the expected CASValidate URL like https://mycas.domain.com/security/serviceValidate?service=https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1, my cas-client tries to validate the ticket with the unexpected login URL - https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1. And this keeps repeating with too many tickets created and finally ending up with too many redirects.

Any help is highly appreciated and would like to know where I need to check the configurations - cas-sever or cas-client? 

Below are the related error details for reference.

_Entering cas_authenticate()
CAS Service 'https%3a%2f%2fmyapp.domain.com%2f'
entering getCASLoginURL()
entering getCASGateway()
entering redirectRequest()
Adding outgoing header: Location: https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f
AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://mycas.domain.com/
AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://mycas.domain.com/
Entering cas_authenticate(), referer: https://mycas.domain.com/
CAS Service 'https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1', referer: https://mycas.domain.com/
entering getCASLoginURL(), referer: https://mycas.domain.com/
entering getCASGateway(), referer: https://mycas.domain.com/
entering redirectRequest(), referer: https://mycas.domain.com/
Adding outgoing header: Location: https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1, referer: https://mycas.domain.com/
AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://mycas.domain.com/
AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://mycas.domain.com/
Entering cas_authenticate(), referer: https://mycas.domain.com/
CAS Service 'https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1', referer: https://mycas.domain.com/
entering getCASLoginURL()
entering getCASGateway()
entering redirectRequest()
Adding outgoing header: Location: https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-126-OWWEa2UNDKy3WSgr9AwZ-sso_ms1%26, referer: https://mycas.domain.com/_

**Comment by harishbabusmiles** [comment]
**1st request after Login:**
Request URL: https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f
Request Method: POST
Status Code: 302 
**Response contains the ticket:**
Response header:
location: https://myapp.domain.com/?ticket=ST-1-FusSGoUyHclydqBlyOvO-sso_ms2

**CAS-Server Redirects the request to my vhost:**
Request URL: https://myapp.domain.com/?ticket=ST-1-FusSGoUyHclydqBlyOvO-sso_ms2
Request Method: GET
Status Code: 302 Found
**Response sent to CASLoginURL, instead of CASValidateURL:**
ResponseHeader:
Location: https://mycas.domain.com/security/login?service=https%3a%2f%2fmyapp.domain.com%2f%3fticket%3dST-1-FusSGoUyHclydqBlyOvO-sso_ms2

I even tried with below RewriteRule when ticket argument hits my app url, **but still not working!**

```
     RewriteEngine On
     RewriteRule ^/$ https://mycas.domain.com/security/serviceValidate/ [PT]
```

**Comment by dhawes** [comment]
I wonder if it's because your tickets have underscores ('_') in them. See the following issue with a quick patch to allow those characters:

https://github.com/apereo/mod_auth_cas/issues/134

**Comment by harishbabusmiles** [comment]
Thank you 👍 - Applied the patch and worked like a charm!!
