### ISSUE TITLE
UTF-8 characters converting to ASCII

### ISSUE THREAD

**Issue by harishbabusmiles** [apereo/mod_auth_cas#198]
One of the CAS header values contains German characters and when I capture it with `request.getHeader` method in my jsp, it gets converted into ASCII. Is there any setting in the mod_auth_cas, which does this conversion?

**Comment by dhawes** [comment]
No, there is no mod_auth_cas directive to do this.

I think in general header values are expected to be US-ASCII. It's possible escaping may be able to be used, but I'd need to research more.

**Comment by dhawes** [comment]
I think this section covers this question:

https://www.rfc-editor.org/rfc/rfc7230#section-3.2

They should be visible US-ASCII characters.
