### ISSUE TITLE
Can mod_auth_cas play nicely with mpm-itk?

### ISSUE THREAD

**Issue by ipimpat** [apereo/mod_auth_cas#200]
Hi I'm trying to get this module working with mpm-itk

My idea is that users can configure CAS authentication them self using htaccess file by simply adding something like `Authtype CAS` to it, how ever I'm also using mpm-itk to seperate privileges (mpm-itk combined with mod_userdir).

But I'm currently hitting a wall with the CASCookiePath setting.

I've changed the permission of the CASCookiePath directory like this:

```
sudo chmod 732 /var/cache/apache2/mod_auth_cas/
sudo chmod o+t /var/cache/apache2/mod_auth_cas/
```

This makes the module "work", because now it can write to directory no matter which user apache is running as.

But I still see this error in the log: 

`[auth_cas:error] [pid 2428806] MOD_AUTH_CAS: Could not create cache metadata file '/var/cache/apache2/mod_auth_cas/.metadata': Permission denied`

As far as I can figure, this happens because the file is read/writeable only to what ever process/owner created that file first.

a) Can the code be changed so it was aware, that is running as different user e.g adding a user/uid prefix/suffix to all files, so the apache process only deals with files it owns?
b) If a configuration option was added so the CASCleanCache function could be disabled completely, could administrators configure their own clean up task using a cronjob?

**Comment by dhawes** [comment]
I'm not that familiar with mpm-itk and have no idea what your config looks like, but could you set a separate CASCookiePath for each VirtualHost?

I expect that either of these modifications could be done. (a) sounds hairy and I'd probably be against it. (b) is possible, but I'd have to be convinced that it is generally useful and not just a one-off.

**Comment by ipimpat** [comment]
mpm-itk allows you to run one or more virtual host as one or more different UID/GID - you can actually do it on "per request" level, which is what I'm doing.

This means that I cannot use multiple cookie paths tho, because I only have one virtual host, and as far as I can read in the source, it can only be set per virtual host, and I don't think it can be set dynamically too, which would also be required.

I'm not set on a particular solution, I don't know if any of my suggestions actually would even work, so for me anything goes :-)

Currently I'm using mpm-itk, with mod_userdir (without mod_auth_cas) for a simple shared development/testing environment for a small group of colleagues, and we currently just use htaccess/htpasswd files to protect directories, but it's a bit of nightmare to manage.

I think mod_auth_cas is perfect fit for us here, because our IT department has an existing CAS service we can use, with a very nice and to our users well known company SSO login page.

This example below is copied from the mpm-itk website, so I would expect other people to do similar stuff:

> AssignUserIDExpr and AssignGroupIDExpr (new in Apache 2.4) are quite powerful, although how to use them is perhaps nonobvious. The easiest way to use them is by combining with mod_rewrite, for instance like this:
> 
> RewriteEngine on
> RewriteRule /~([a-z]+)/ - [E=ITKUID:$1]
> AssignUserIDExpr %{reqenv:ITKUID}
> 
> This will cause e.g. /~sesse/foo to be run as the user “sesse” (and /~root/foo to be run as user “root”, so beware!).

http://mpm-itk.sesse.net/ (Configuration section)

When you combine the above example with mod_userdir, the user part of the requested path will be aliased to `/home/sesse/public_html` and the beauty of that is that I only have one virtual host configuration file to deal with (the default one) and each user's public_html directory in their home directory is served as their owners identity.

My idea is that if mod_auth_cas could be added on top of this, then my colleagues can easily protect their public_html folder as they see fit, with just a few simply lines in a .htaccess file.

This is simply example of how a `/home/<user>/public_html/.htaccess` file could look like, to protect the entire content of a user's public_html folder:

```
Authtype CAS
Require valid-user
```

This is currently how my virtual host configuration looks like:

`/etc/apache2/sites-enabled/default-ssl.conf`

```
<VirtualHost _default_:443>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SetEnvIf Request_URI (.+) ITKUID=www-data ITKGID=www-data            # Set request variables ITKUID and ITKGID, just to make sure they have a default sane value
    SetEnvIf Request_URI ^/~([a-z]+)/ ITKUID=$1 ITKGID=$1                # Set the ITKUID=foo, ITKGID=foo if request uri is /~foo
    SetEnvIf ITKUID ^root$ ITKUID=www-data                               # But if ITKUID or ITKGID set to root, we set them back to www-data
    SetEnvIf ITKGID ^root$ ITKGID=www-data

    DocumentRoot /var/www/html

    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory "/home/*/public_html">                                    
        AssignUserIDExpr %{reqenv:ITKUID}                                # Run as the user defined in ITKUID / ITKGID inside user's public_html directory
        AssignGroupIDExpr %{reqenv:ITKGID}                              

        AllowOverride all
        php_admin_flag engine On
    </Directory>
    <Directory /usr/lib/cgi-bin>
        SSLOptions +StdEnvVars
    </Directory>

</VirtualHost>
```

This is the default userdir configuration shipped on Debian/Ubuntu:

`/etc/apache2/mods-enabled/userdir.conf`

```
<IfModule mod_userdir.c>
	UserDir public_html
	UserDir disabled root

	<Directory /home/*/public_html>
		AllowOverride FileInfo AuthConfig Limit Indexes
		Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
		Require method GET POST OPTIONS
	</Directory>
</IfModule>
```

**Comment by dhawes** [comment]
I'd be more inclined to look at this further if it was a native feature of Apache that wasn't supported. This is not something I'd have time to take on, but patches are always welcome. A patch for something like this with serious security implications would almost certainly be scrutinized more than usual.
