### ISSUE TITLE
About distributed sessions

### ISSUE THREAD

**Issue by hxdy-a** [apereo/mod_auth_cas#201]
Hi, my Apache server is deployed in clusters. Is there any distributed session solution. Tks.

**Comment by dhawes** [comment]
There is not, other than putting CASCookiePath on an NFS partition. I've never personally tested that solution, but I believe others have had success with it. There may have been issues with older Linux kernels with flock() over NFS, but this appears to not be an issue in later kernels, as reported by the flock() man page.

**Comment by hxdy-a** [comment]
Ok thanks for your answer
