### ISSUE TITLE
The url is long and has query failed to login

### ISSUE THREAD

**Issue by zy2324** [apereo/mod_auth_cas#206]
Hello, I have a problem recently.
Such as my website is newweb.office.top, when first cas login with
https://mycas.domain/cas/login?service=http://newweb.office.top/
It is login normal, and no errors for me.

But when I use 
http://newweb.office.top/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=xxx, first cas login with
https://mycas.domain/cas/login?service=http://newweb.office.top/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=xxx/
It login ok, but visit the website resources in somewhere will error and get complete website failed.

I check the network process, it always failed in one url. http code is 302 but no packets.
![image](https://user-images.githubusercontent.com/24699311/180116782-b8aeb612-680b-4bb5-b4b7-6ea13fb4e11e.png)

But when I use this error url(picture I point. one) to login with cas, it is normal again. 

It can recurrence in other website. I find the same place is:
http://example.com,  http://example.com/a will login normally.
http://example.com/a/b or http://example.com/a/b?xx=1&yy=2 will login ok, but always get failed in one url.

I had add ap_log_rerror in mod_auth_cas.c for find the reason why, but still can't solve it. 
Can anyone face the same problem and solved it?
Thank you.

**Comment by zy2324** [comment]
Anyone who can take a look

**Comment by dhawes** [comment]
What version of Apache and mod_auth_cas are you using? What does your configuration look like?

Can you share the simplest httpd.conf config that recreates the issue you are seeing? I'm having difficulty understanding what your issue is without more clarification.

**Comment by zy2324** [comment]
apache2 version: Apache/2.4.37
mod_auth_cas version: clone the latest code and make install for using.

my conf
```shell
LoadModule auth_cas_module /usr/lib/apache2/modules/mod_auth_cas.so
CASDebug On
CASCookiePath /var/cache/apache2/mod_auth_cas/
CASLoginURL https://auth.example.ss/cas/login
CASValidateURL https://auth.example.ss/cas/serviceValidate


<VirtualHost *:80>
    ServerName newgraphs.office.iis.ii
    LogLevel Debug
    <Location />
        Authtype CAS
        Require valid-user
    </Location>
    ProxyPass "/" "http://localhost:18190/"
    ProxyPassReverse "/" "http://localhost:18190/"
    ProxyPreserveHost On
</VirtualHost>
```

Clear introduction, the problem now is:
when I login with newgraphs.office.iis.ii or newgraphs.office.iis.ii/first, I can login succeed and visit web site normally.

when I login with  newgraphs.office.iis.ii/first/second or newgraphs.office.iis.ii/first/second/third?xx=1&yy=2&zz=3, I can login succeed but web site get error, can't visit web site with some one url when load.

**Comment by dhawes** [comment]
What error does your web site show? Do your Apache logs indicate an issue with mod_auth_cas? Be sure to set "CASDebug On".

**Comment by zy2324** [comment]
I want to say my guess conclusion firstly:
**The url, if has two and more subpaths, http://newgraphs.office.iis.ii/a/b or http://newgraphs.office.iis.ii/a/b/c?xx=1&yy=2 , can login succeed but get website data maybe has bug**


When I first login: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp

This is the web error:
![image](https://user-images.githubusercontent.com/24699311/180940434-25e30731-492d-477c-b93b-08468f789544.png)
I can login succeed, but give me error.Then this is the debug that I can see failed in http://newgraphs.office.iis.ii/api/dashboards/uid/cb-FPC2mk
![image](https://user-images.githubusercontent.com/24699311/180940222-03160fad-a08b-4e93-a5b3-8d8d8f14aef1.png)
![image](https://user-images.githubusercontent.com/24699311/180941729-03a3dc21-b308-4650-b7c6-00a4a97b24fa.png)
![image](https://user-images.githubusercontent.com/24699311/180941278-041c1e22-4530-4845-98e2-997fb41242ac.png)
The log I catch this url about:
```
[Tue Jul 26 14:36:11.191227 2022] [authz_core:debug] [pid 27107:tid 140661529446144] mod_authz_core.c(820): [client 172.23.172.101:57620] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191259 2022] [authz_core:debug] [pid 27107:tid 140661529446144] mod_authz_core.c(820): [client 172.23.172.101:57620] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191276 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(2183): [client 172.23.172.101:57620] zhaoyi cas_authenticate fisrt is ~(null) ~(null) ~(null) ~proxy:http://localhost:18190/api/dashboards/uid/cb-FPC2mk ~/api/dashboards/uid/cb-FPC2mk ~/api/dashboards/uid/cb-FPC2mk ~(null) ~(null) ~(null), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191282 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(2203): [client 172.23.172.101:57620] Entering cas_authenticate(), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191286 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(796): [client 172.23.172.101:57620] zhaoyi debug cookieName MOD_AUTH_CAS, referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191291 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(798): [client 172.23.172.101:57620] zhaoyi debug rv (null), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191294 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(2209): [client 172.23.172.101:57620] zhaoyi debug ticket:(null) cookieString:(null), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191298 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(616): [client 172.23.172.101:57620] zhaoyi debug r-uri:/api/dashboards/uid/cb-FPC2mk r->parsed_uri.path:/api/dashboards/uid/cb-FPC2mk, referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191302 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(627): [client 172.23.172.101:57620] zhaoyi debug how to change url 1 r->server->server_hostname newgraphs.office.iis.ii port_str  escapeString(r, r->uri) %2fapi%2fdashboards%2fuid%2fcb-FPC2mk r->args (null), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191306 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(644): [client 172.23.172.101:57620] CAS Service 'http%3a%2f%2fnewgraphs.office.iis.ii%2fapi%2fdashboards%2fuid%2fcb-FPC2mk', referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
[Tue Jul 26 14:36:11.191310 2022] [auth_cas:debug] [pid 27107:tid 140661529446144] mod_auth_cas.c(585): [client 172.23.172.101:57620] entering getCASLoginURL(), referer: http://newgraphs.office.iis.ii/d/cb-FPC2mk/data-center-resources?orgId=1&from=1639378166190&to=1639411404949&var-cluster=datacenter&var-region=imo-ap-sgp
```

And then, when I first visit http://newgraphs.office.iis.ii/api/dashboards/uid/cb-FPC2mk
![image](https://user-images.githubusercontent.com/24699311/180944167-f4e4efb9-7247-40db-af73-643167abd450.png)
![image](https://user-images.githubusercontent.com/24699311/180943316-d27f41bf-de45-4a0b-b686-0150f9e3eb4d.png)
![image](https://user-images.githubusercontent.com/24699311/180944299-f4998e86-2ebf-499e-b3f9-86fb0dec9aa2.png)

I can login and get the website normally . This url gives me some json data.

**Comment by dhawes** [comment]
You  mention that you are using git master. Do you get the same behavior with HEAD~ [1] ? 

[1] https://github.com/apereo/mod_auth_cas/commit/de41363d23618f098673575961b2cce521e0902b?

**Comment by zy2324** [comment]
Yes, get the same. I check the code now.

**Comment by dhawes** [comment]
A lot of what you're posting is application-specific to the app behind mod_auth_cas. What makes you believe that this is a mod_auth_cas issue and not something with the app itself?

If you can post just the Apache error log (preferably without your modifications) for your issue, that would help a lot.

**Comment by zy2324** [comment]
emmm, can you give a email for me that I could send the all apache log for you.Or my email is zyyyyyy2324@163.com, you can give a email first. Hope we could talk about this together.
And btw, I am sure for the mod_auth_cas issue is that if I don't load mod_auth_cas., the application is always normlly.

**Comment by dhawes** [comment]
Are you unable to upload it here? I'd prefer to keep everything on this issue. The logs would preferably be setup for the minimal mod_auth_cas config that displays the issue.

The images you upload show CORS issues that should be resolved before we look any further. Something like this may help:

https://enable-cors.org/server_apache.html
https://stackoverflow.com/questions/42337877/change-grafanas-headers-access-control-allow-origin

**Comment by zy2324** [comment]
In fact, I try this way before, it also no good for me. I config it today again, also error.

**I don't load mod_auth_cas, my application is normally. I am also not set header config.All is normally to visit**

After load mod_auth_cas, there has error. So I think it is obvious that mod_auth_cas affect.How you think of it.

All log I visit the application after load mod_auth_cas, that many logs. I wan to send email for you.

**Comment by dhawes** [comment]
What specifically did you try? A minimal mod_auth_cas config without the app you are trying to protect, or setting up CORS?

All of the errors you are posting look to me to browser-related CORS issues. This is because mod_auth_cas redirects you to your CAS server, but that does not mean that it is explicitly a mod_auth_cas issue.

I suggest adding config to get rid of those CORS issues. When that's fixed if you still have issues, we can look at the Apache logs.

**Comment by zy2324** [comment]
I know what your mean. **But**

I have another website, the error is different above it. Also, not load mod_auth_cas, visit normally.After load mod, most visit well, but sometimes failed in one url with http://url/a/b (two subpath, like my said before). Let me show.

1.no load mod_auth_cas
result: everything is ok

2.load mod_auth_cas
url: http://resourcemanager.office.ixx.ix
result: everything is ok

3.load mod_auth_cas
url:http://resourcemanager.office.ixx.ix/shards/Sysmon
result:login cas is ok, but website process failed in one url.The error is different from above.
This is picture:
![image](https://user-images.githubusercontent.com/24699311/181410457-53a67eff-c2b5-4a7d-b152-830b9b0f978f.png)
cas login page is well.And can login in.

![image](https://user-images.githubusercontent.com/24699311/181409531-5c86a3c1-5f8f-4a33-a878-f93a458d57af.png)
the network process no error. But web site can't get data. Then check the console, it has error
![image](https://user-images.githubusercontent.com/24699311/181409774-bc7052ec-74d6-4b2c-80ba-65abba5de2e3.png)

**Comment by zy2324** [comment]
So before I said:

The url, sometimes if has two and more subpaths, http://xxx.office.iis.ii/a/b or http://xxx.office.iis.ii/a/b/c?xx=1&yy=2 , can login succeed but visit website data maybe has bug when get some url

This is still my conclusion.So I am hope that you can think about it.

**Comment by zy2324** [comment]
I use the http://xxx/office.iis.ii first, the log I debug, cookie is still the one cookieString, even if after load the subpath.

But when fisrt login with two or more subpath, http://xxx/office.iis.ii/a/b... , I debug log, that can see some different cookieString. 

BTW, In your code, I add log, such as in getCASService, cas_authenticate, rv, cookieString...

**Comment by zy2324** [comment]
Oh, I maybe find reason?

**Comment by dhawes** [comment]
What are seeing is likely a bug in git master [1]. Either set "CASScope /" in your config or revert to HEAD~ [2].

You can see if this is affecting you by inspecting your cookies. If there are multiple mod_auth_cas cookies, you're probably affected. You can also check your logs for something like:

```
AH00011: ap_cookie: client submitted cookie 'MOD_AUTH_CAS_S' more than once: /first/second/
```

Try the above, fix the CORS issues for your other app, and then we can inspect Apache logs if a problem is still present.

[1] https://github.com/apereo/mod_auth_cas/pull/202#issuecomment-1196161021
[2] https://github.com/apereo/mod_auth_cas/commit/de41363d23618f098673575961b2cce521e0902b

**Comment by zy2324** [comment]
I try what you say. And set "CASScope /" seems is helpful for me. 

Thanks a lof for talking with me. Let me use mod_auth_cas continue.

**Comment by zy2324** [comment]
hi dhawes, there are some logs:
ap_cookie: client submitted cookie 'MOD_AUTH_CAS' more than once: /tasks_json/, referer: 

It maybe another problem.Do you have some suggest...

**Comment by dhawes** [comment]
Is this after reverting to a commit that's not git master? Have you removed all cookies in your browser before trying again?

**Comment by zy2324** [comment]
yes, maybe about browser cookies.Now not affect visit. I will continue to use and observe.

**Comment by dhawes** [comment]
The change to revert cookie parsing is now in git master. 

Closing this issue.
