### ISSUE TITLE
pcre-devel deprecated

### ISSUE THREAD

**Issue by thansen11** [apereo/mod_auth_cas#208]
I'm currently working on unretiring the mod_auth_cas package for fedora based systems.  In the review process its been noted that the build requires pcre-devel which is a deprecated package.  Its been suggested that I ask if there is interest in porting this over to pcre2?

Please see the following bugzilla comment for reference: https://bugzilla.redhat.com/show_bug.cgi?id=2173751#c8

**Comment by vwbusguy** [comment]
FYI, I tested the pull request against the spec, swapping out for `pcre2-devel`, and it builds the RPM without error.
