### ISSUE TITLE
CASLoginURL and CASValidateURL requires authentication.

### ISSUE THREAD

**Issue by harishbabusmiles** [apereo/mod_auth_cas#212]
Hi, 
I have a scenario where the defined CAS instance in CASLoginURL and CASValidateURL is enabled with basic authentication. Is there a way to pass on the credentials to the CAS instance URLs ? Without this authenticated, I get the below response. 

_Entering cas_check_authorization., referer: https://myapp.domain.com/
AH01626: authorization result of Require cas-attribute EmailStatus:Active: denied (no authenticated user yet), referer: https://myapp.domain.com/
AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://myapp.domain.com/
Entering cas_authenticate(), referer: https://myapp.domain.com/
Modified r->args (now ''), referer: https://myapp.domain.com/
entering getResponseFromServer(), referer: https://myapp.domain.com/
CAS Service 'https%3a%2f%2fmyapp.domain.com', referer: https://myapp.domain.com/
Validation response: 401 Unauthorized\nYou need a valid user and password to access this content.\n, referer: https://myapp.domain.com/
entering isValidCASTicket(), referer: https://myapp.domain.com/
MOD_AUTH_CAS: response = 401 Unauthorized\nYou need a valid user and password to access this content.\n, referer: https://myapp.domain.com/_

Any help is appreciated. Thanks in advance.

**Comment by dhawes** [comment]
There is no way to do this currently, but I'd expect something like the following to work:

```
diff --git a/src/mod_auth_cas.c b/src/mod_auth_cas.c
index a3c5561..f318b28 100644
--- a/src/mod_auth_cas.c
+++ b/src/mod_auth_cas.c
@@ -1876,6 +1876,7 @@ char *getResponseFromServer (request_rec *r, cas_cfg *c, char *ticket)
        curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, curlError);
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 5L);
+       curl_easy_setopt(curl, CURLOPT_USERPWD, "clark:kent");
 
        curlBuffer.buf = NULL;
        curlBuffer.written = 0;

```
