### ISSUE TITLE
During ./configure run configure: error: libpcre2 required

### ISSUE THREAD

**Issue by dannymk** [apereo/mod_auth_cas#215]
Trying to run the ./configure script on a freshly pulled project causes the following error:

```
checking for openssl/err.h... yes
checking for gawk... (cached) mawk
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.81.0
checking whether libcurl is usable... yes
checking for curl_free... yes
checking for pcre2_compile in -lpcre2... no
configure: error: libpcre2 required
```

Tried installing it again when it was obviously already installed:

```
root@80342ca08343:/usr/src/mod_auth_cas# apt -y install libpcre2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpcre2-dev is already the newest version (10.39-3ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
root@80342ca08343:/usr/src/mod_auth_cas# 
```

I have set:  

`export LD_LIBRARY_PATH=/usr/local/lib:/lib:/usr/lib:/usr/lib/x86_64-linux-gnu/`

and still no dice!

**Comment by dhawes** [comment]
Can you run `autoreconf -ivf`, and then try your `configure` line?

**Comment by dannymk** [comment]
Hmmm.... that worked.  The "autoreconf -ivf" came after "configure" in the Dockerfile when I switched them it worked.

Thank you.

**Comment by dhawes** [comment]
The libpcre2 changes were from a recent commit, so we likely need to update configure as well. Sorry me missed that, I hope to address it soon.

**Comment by dhawes** [comment]
Would you mind testing this branch without running `autoreconf -ivf`?

https://github.com/apereo/mod_auth_cas/pull/216

**Comment by dannymk** [comment]
Using your repo I got passed the above reported issue but receive an error during make:

:/usr/src/mod_auth_cas# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /usr/src/mod_auth_cas/missing aclocal-1.15 -I m4
/usr/src/mod_auth_cas/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:398: aclocal.m4] Error 127

**Comment by vwbusguy** [comment]
> WARNING: 'aclocal-1.15' is missing on your system.
> You should only need it if you modified 'acinclude.m4' or
> 'configure.ac' or m4 files included by 'configure.ac'.
> The 'aclocal' program is part of the GNU Automake package:
> http://www.gnu.org/software/automake
> It also requires GNU Autoconf, GNU m4 and Perl in order to run:
> make: *** [Makefile:398: aclocal.m4] Error 127

Yeah, you'll want automake, autoconf, and m4 in addition to gcc.  It doesn't require perl itself, but the PCRE2 development headers for C.  

Ref. https://src.fedoraproject.org/rpms/mod_auth_cas/blob/main/f/mod_auth_cas.spec
