### ISSUE TITLE
Can't access REMOTE_USER in mod_rewrite scripts

### ISSUE THREAD

**Issue by sarcasticsys** [apereo/mod_auth_cas#68]
Not sure if this is a bug or a feature request (apologies in advance if this is the wrong place), but I have a use case where we want to take the REMOTE_USER (as set by CAS) and set a specific environment value (AJP_REMOTE_USER, so that mod_proxy_ajp will pass REMOTE_USER to the backend server) to this value and am running into issues.  Looking online, I tried some mod_rewrite tricks like below:

RewriteCond %{LA-U:REMOTE_USER} (.+)
RewriteRule .\* - [E=AJP_REMOTE_USER:%1]

(or just using %{REMOTE_USER}) but it doesn't seem to work and debugging mod_rewrite shows it thinking that the value of REMOTE_USER is null.  This seems to be related to he issue talked about briefly here: https://github.com/aimxhaisse/mod-proxy-add-user which suggests that some auth modules set REMOTE_USER in a way that makes it unavailable to mod_rewrite but I confess to not knowing much about Apache module internals.

Environment where I've seen the behavior is RHEL6.5, httpd-2.2.15-30.0.1.el6_5.x86_64, and mod_auth_cas-1.0.9-1 from the EPEL repositories and a fresh build of mod_auth_cas from the git repository.

I worked around the issue a little bit by patching a local copy of mod_auth_cas to implement a feature called CASAuthNEnv that is basically similar to CASAuthNHeader except populating a given environment variable instead of a header  The idea being that you can just set something like:
CASAuthNEnv AJP_REMOTE_USER in your Apache conf.

It seems to work in a test environment but I admit to not knowing C or APR so I have no idea if I am doing something horrifyingly wrong - it amounts to setting up the config option and calling:

apr_table_add(r->subprocess_env,d->CASAuthNEnv,remoteUser);
when appropriate.

I have no idea if my use case is extreme edge or if I'm running into a configuration issue, but it'd be a valuable option for my environment at least! (vendor I'm working with doesn't want the header passed via headers, only environment variables).

**Comment by dhawes** [comment]
Your mod_rewrite tricks work for me with Apache 2.4 and mod_auth_cas master. Both the normal and lookahead RewriteCond(s) add AJP_REMOTE_USER to the environment.

It's possible your solution may be generally useful. I can see where it may be nice to add attributes to the Apache environment. 

I'm closing this issue for now. Reopen if you want to pursue it further if later software versions don't work for you.
