### ISSUE TITLE
Option to disable removeCASParams

### ISSUE THREAD

**Issue by jamgregory** [apereo/mod_auth_cas#69]
Would it be possible to provide an option which disables the cleaning of the 'ticket' param from the query string?

The rationale behind this is that we have some demo apps which are protected by CAS on Apache, and then also have CAS authentication within the app which will be used when the system goes live. This currently means that the internal CAS authentication doesn't work because the ticket attribute is scrubbed by Apache.

**Comment by dhawes** [comment]
See #158.
