### ISSUE TITLE
CASScope should be available on Server level too

### ISSUE THREAD

**Issue by sathieu** [apereo/mod_auth_cas#83]
We want to have "CASScope /" by default, how to?

**Comment by dhawes** [comment]
This issue has been open for a while now with no responses. Users don't seem to need this. Closing.

**Comment by jamgregory** [comment]
I've just been banging my head against this. I think it would also be sensible for this to be at server-level, or for the default to be the root (i.e. `CASScope /`) rather than off entirely.
